"""I testi fissi: disclaimer e messaggi di sicurezza.

Stanno nel codice e non nel prompt perché non devono dipendere dal modello:
il disclaimer si mostra identico a ogni lettura, all'inizio e alla fine, e il
messaggio di crisi non può essere riformulato da nessuno.
"""
from __future__ import annotations

DISCLAIMER = {
    "it": (
        "Questa è una lettura dei tarocchi generata da un'intelligenza artificiale, "
        "condotta con rigore e coerenza secondo la tradizione esoterica del Tarocco "
        "di Thoth. Non è una certezza: descrive il più probabile dei futuri alla luce "
        "delle forze che le carte mostrano adesso, e le tue scelte possono cambiarlo. "
        "Non esiste alcuna base scientifica che dimostri la validità delle previsioni "
        "dei tarocchi: usala come uno specchio per riflettere, non come una sentenza."
    ),
    "en": (
        "This is a tarot reading generated by an artificial intelligence, carried out "
        "with rigour and coherence according to the esoteric tradition of the Thoth "
        "Tarot. It is not a certainty: it describes the most probable of futures in the "
        "light of the forces the cards show now, and your choices can change it. There "
        "is no scientific evidence that tarot predictions are valid: use it as a mirror "
        "for reflection, not as a verdict."
    ),
}

AIUTO = {
    "it": (
        "Sento che stai attraversando un momento molto doloroso, e non voglio che le "
        "carte si mettano fra te e l'aiuto di cui hai bisogno adesso. Non sei solo o "
        "sola: puoi parlare subito con qualcuno.\n\n"
        "- **Emergenza:** 112\n"
        "- **Telefono Amico Italia:** 02 2327 2327 (anche via chat su telefonoamico.it)\n"
        "- **Samaritans Onlus:** 06 77208977\n\n"
        "Se puoi, contatta anche una persona di cui ti fidi o il tuo medico. "
        "La lettura è stata sospesa e il credito ti è stato restituito."
    ),
    "en": (
        "It sounds like you are going through something very painful, and I don't "
        "want the cards to stand between you and the help you need right now. You "
        "are not alone: you can talk to someone immediately.\n\n"
        "- **Emergency:** 112 (EU) / 911 (US)\n"
        "- **Find a helpline:** findahelpline.com\n\n"
        "If you can, also reach out to someone you trust or to your doctor. "
        "The reading has been paused and your credit refunded."
    ),
}

RESPONSO_BLOCCATO = {
    "it": (
        "Le carte di questa lettura toccano temi che richiedono più delicatezza di "
        "quanta una lettura automatica possa garantire. Preferisco non darti un "
        "responso che potrebbe farti del male o spingerti a decisioni che meritano "
        "l'aiuto di una persona competente. Puoi rileggere le singole carte qui sopra "
        "come spunti di riflessione, e se stai attraversando un momento difficile "
        "parlane con qualcuno di cui ti fidi."
    ),
    "en": (
        "The cards in this reading touch on themes that require more care than an "
        "automated reading can guarantee. I prefer not to give you a verdict that "
        "could harm you or push you towards decisions that deserve the help of a "
        "competent person. You can reread the individual cards above as prompts for "
        "reflection, and if you are going through a hard time, talk to someone you trust."
    ),
}

DOMANDE_DI_RISERVA = {
    "it": [
        "Da quanto tempo questa situazione è presente nella tua vita, e cosa l'ha messa in moto?",
        "Chi sono le persone coinvolte, e che ruolo hanno per te?",
        "Cosa è già successo finora che ti sembra importante per capire il quadro?",
        "Come ti senti, in questo periodo, quando pensi a questa situazione?",
        "C'è una decisione o un passaggio che si avvicina, e in quali tempi?",
    ],
    "en": [
        "How long has this situation been part of your life, and what set it in motion?",
        "Who are the people involved, and what role do they play for you?",
        "What has already happened that seems important to understand the picture?",
        "How do you feel, these days, when you think about this situation?",
        "Is there a decision or a step approaching, and on what timescale?",
    ],
}


def lingua(lang: str) -> str:
    return "en" if (lang or "").lower().startswith("en") else "it"
