"""Scene per le immagini delle carte: Bastoni (Wands). Una scena per carta, in inglese."""

SCENE = {
    "bastoni-01": (
        "A single colossal primordial torch-wand of the element of Fire rises vertically through the "
        "exact centre of the image, filling almost the entire height, set against a vast dark void that "
        "bursts into radiance around it. The wand is a rough, living club of raw wood fused with molten "
        "gold, cracked open to reveal glowing magma within. From its crown and from its knots leap ten "
        "separate flames, each shaped like the Hebrew letter Yod (י, a small comma-like tongue of fire, "
        "the seed-letter of all creation), and these ten flames are arranged precisely in the pattern of "
        "the Kabbalistic Tree of Life (ten points in three vertical columns joined by faint lines), drawn"
        " clearly and symmetrically. Above the topmost flame burns a tiny point of pure white light "
        "representing Kether (the Crown, the first sephira, undivided brilliance). Behind the wand a "
        "great upward-pointing triangle, the alchemical sign of Fire (a simple equilateral triangle with "
        "its apex up), is traced in thin lines of light, drawn precisely. Sparks, solar spirals and "
        "whirling embers radiate outward in every direction like the birth of a star; there are no "
        "figures, no landscape, only force. Palette: blinding white-gold core (#F5F3E7), flame scarlet-"
        "orange (#D2461E), molten amber (#FF9F1C) and deep smoky black at the edges (#140A06). The light "
        "comes from the wand itself, the only source in the image. The whole image should feel like the "
        "first explosive spark of pure will before it has any shape or aim, raw creative power erupting "
        "from nothing."
    ),
    "bastoni-02": (
        "A strictly symmetrical, emblematic composition of two wands of Fire, with no human figures. In "
        "the centre, two great Tibetan dorjes (vajra thunderbolt-sceptres: a central grip with two "
        "flared, clawed prongs at each end) form a tall upright X, crossing at their grips over a burning"
        " point of scarlet light. Each prong of each dorje ends in a small fanged serpent head breathing "
        "a tongue of flame, so that eight small jets of fire spit outward toward the corners, suggesting "
        "power that destroys in order to create. Around the crossing, in the middle ground, a ring of "
        "forked lightning connects the four ends like a charged circuit. In the upper left corner the "
        "astrological glyph of Mars (♂, a circle with an arrow pointing up-right) and in the upper right "
        "corner the glyph of Aries (♈, two curved horns joined at the base like a ram's head) glow in "
        "scarlet, both drawn precisely and clearly. The background is the silver-grey of Chokmah (Wisdom,"
        " the second sephira, the pure masculine creative force, the first outrush of energy), a soft "
        "luminous pearly-grey mist with faint radiating lines like a banner of command. Palette: pearl "
        "grey (#8A8D8F), silver (#C0C4C8), fierce Mars scarlet (#D2461E), blood crimson (#9E1B1B) and "
        "white-hot highlights on the dorje metal. The light radiates from the crossing point at the "
        "centre. The mood is imperious and electric: the whole image should feel like Dominion, a will "
        "seizing command of its own raw force and aiming it outward with fearless authority."
    ),
    "bastoni-03": (
        "A vertical, triangular composition of three wands of Fire, with no human figures. Three slender "
        "golden rods rise from a single burning point at the bottom centre and fan out upward to form an "
        "upright triangle, the shape of the third sephira. Each wand ends at the top in a lotus flower "
        "just opening, its pale petals rimmed in flame, and from inside each lotus a soft sunrise light "
        "spills upward. The three lotuses sit at the three points of a faint downward-facing triangle of "
        "light, so the whole forms a balanced, flowering structure. Behind them a large dawn sun disc is "
        "rising, rendered with rays like spokes. The background is the deep black of Binah "
        "(Understanding, the third sephira, dark, maternal and Saturnine, the great sea that gives form),"
        " and the dawn breaks out of this darkness as if the womb of night were giving birth to spring. "
        "At the top, drawn precisely and clearly in gold, are the glyph of the Sun (☉, a circle with a "
        "dot in its centre) and the glyph of Aries (♈, two curved horns joined at the base like a ram's "
        "head). Small green buds sprout along the wands to hint at spring. Palette: velvet black "
        "(#1A1A1A), dawn gold (#F2C14E), rose-pink lotus (#F4A7B9), flame orange-red (#D2461E) and a thin"
        " line of spring green (#6BBF59). Light rises from the lotuses and the sun at the top. The whole "
        "image should feel like Virtue, first noble success, integrity blossoming like the fire of spring"
        " out of silent darkness."
    ),
    "bastoni-04": (
        "A circular, wheel-like composition of four wands of Fire, with no human figures. Four ornate "
        "golden wands are set as the four spokes of a great horizontal-and-vertical cross inside a "
        "perfect circle, so the image reads as a stable, radiant wheel centred in the frame. Each wand "
        "carries a ram's head at one end and a white dove at the other, alternating around the wheel, so "
        "that four ram heads and four doves face outward in a balanced rhythm (the ram for Mars and "
        "energy, the dove for Venus and love). The rim of the wheel is a band of steady flame, neither "
        "leaping nor dying, like a hearth kept perfectly. At the hub glows a small square of sapphire "
        "light, a reminder that four is the number of form and order. The background is the royal blue of"
        " Chesed (Mercy, the fourth sephira, the benevolent ordering king, ruled by Jupiter), deep and "
        "calm, scattered with faint golden stars. In the upper left the glyph of Venus (♀, a circle with "
        "a small cross beneath it) and in the upper right the glyph of Aries (♈, two curved horns joined "
        "at the base like a ram's head) shine in soft gold, both drawn precisely and clearly. Palette: "
        "royal blue (#1F4E9A), sky-violet shadows (#3B3F8F), festive gold (#E6B422), flame red-orange "
        "(#D2461E) and dove white (#F7F4EC). Warm light comes evenly from the flaming rim. The whole "
        "image should feel like Completion: force and love united in a perfect circle, a celebration of "
        "work achieved and securely established."
    ),
    "bastoni-05": (
        "A tense, clashing composition of five wands of Fire, with no human figures. In the centre stands"
        " one great vertical chief wand, heavy and dark-gold, crowned with a winged solar globe (a sphere"
        " with outspread falcon wings, symbol of the highest initiate) and resting on a stone base. "
        "Against it, four lesser wands cross diagonally in an X from the corners, two topped with small "
        "phoenix heads and two with lotus buds, all pressing against the central wand so that their "
        "shafts grind together and sparks spray from every point of contact. The flames are thick, smoky "
        "and struggling, bent sideways as if under a great weight. Around the crossing, a pentagon of "
        "fire (a five-sided figure outlined in flame, the shape of Geburah's number) is drawn clearly, "
        "slightly distorted by the pressure. The background is the harsh scarlet of Geburah (Severity, "
        "the fifth sephira, the warrior force of Mars, discipline and destruction), streaked with ash-"
        "grey smoke. Heavy lead-grey clouds press down from the top. In the upper corners, drawn "
        "precisely and clearly, glow the glyph of Saturn (♄, a cross whose lower end curls into a hook "
        "like a sickle) and the glyph of Leo (♌, a looping line like a lion's mane ending in a curled "
        "tail). Palette: scarlet (#C8102E), flame orange (#D2461E), lead grey (#5A5A5E), soot black "
        "(#1C1414) and dull gold (#B08D2A). Harsh light flares from the points of collision. The whole "
        "image should feel like Strife: fiery energy fighting against a crushing Saturnian weight, "
        "struggle that tempers the will."
    ),
    "bastoni-06": (
        "A harmonious, perfectly symmetrical composition of six wands of Fire, with no human figures. Six"
        " golden wands are arranged as three pairs crossing in a regular pattern, forming a luminous "
        "hexagram (a six-pointed star of two interlaced triangles, one pointing up and one down), drawn "
        "precisely and centred. The wand ends are topped alternately with small winged solar globes, "
        "phoenix heads and lotus buds, all orderly and matching. Nine steady flames burn in a calm row "
        "across the lower part of the star, upright and even, never flickering. At the heart of the "
        "hexagram shines a radiant golden sun, representing Tiphareth (Beauty, the sixth sephira, the "
        "solar heart of the Tree of Life, harmony and balance). Laurel branches frame the lower corners, "
        "suggesting a crown of triumph. The background is a clear gold and warm amber sky with fine "
        "radiating rays, like a banner of victory. At the top centre, drawn precisely and clearly in "
        "bright gold, appear the glyph of Jupiter (♃, a stylised number 4 with a curved left arm) and the"
        " glyph of Leo (♌, a looping line like a lion's mane ending in a curled tail). Palette: solar "
        "gold (#E6B422), rich yellow (#FFD34E), flame orange-red (#D2461E), laurel green (#4F7A3A) and "
        "warm rose-amber (#F2A65A). Light radiates evenly from the central sun. The mood is serene and "
        "triumphant. The whole image should feel like Victory: disciplined energy winning through balance"
        " rather than violence, the will aligned with the heart."
    ),
    "bastoni-07": (
        "A bold composition of seven wands of Fire, with no human figures, built on an asymmetric "
        "contrast. In the middle ground, six refined wands with ornate tips (winged globes, phoenix "
        "heads, lotus buds) are crossed in a neat lattice, their flames low and tangled, as if the "
        "orderly company were hard pressed. In the foreground, rising vertically straight through the "
        "centre in front of them, stands a single crude club of raw, knotted wood, rough-hewn and "
        "unpolished, bigger than the others, with a fierce, clean flame at its top: individual courage "
        "standing in for collective discipline. Around the club, flame-sparks fly outward in a sevenfold "
        "star (a heptagram, a seven-pointed star drawn in one continuous line), drawn precisely and "
        "clearly. The background is the emerald green of Netzach (Victory, the seventh sephira, the "
        "sphere of Venus, of passion and instinct, where force is felt rather than planned), deep and "
        "forest-like, crossed by smoky shadows as of a battlefield at dusk. In the upper corners, glowing"
        " red and drawn precisely and clearly, appear the glyph of Mars (♂, a circle with an arrow "
        "pointing up-right) and the glyph of Leo (♌, a looping line like a lion's mane ending in a curled"
        " tail). Palette: emerald green (#2E8B57), dark pine (#16402A), flame red-orange (#D2461E), raw "
        "wood brown (#6B4423) and ember yellow (#F4B942). A hard, dramatic light falls from the flame of "
        "the crude club. The whole image should feel like Valour: standing one's ground with raw courage "
        "against the odds."
    ),
    "bastoni-08": (
        "A dynamic, diagonal composition of eight wands of Fire, with no human figures and no ordinary "
        "wood. The eight wands are rendered as rods of pure electric light, shooting diagonally from the "
        "lower left to the upper right like bolts of lightning, parallel in two groups of four, crossing "
        "each other in the centre to draw a luminous geometric solid (a translucent octahedron, a double "
        "pyramid of eight triangular faces, drawn precisely). Each rod ends in an arrow-point of white "
        "light. Above them arches a clear rainbow, a bridge of spectrum colours, and fine lines of force "
        "ripple outward like waves, suggesting sound, speech and messages travelling at the speed of "
        "thought. The background is the warm orange of Hod (Splendour, the eighth sephira, the sphere of "
        "Mercury, intellect, language and swift communication), glowing like a sky full of static. Along "
        "the arrows' path, drawn precisely and clearly in bright white, are the glyph of Mercury (☿, a "
        "circle with a small cross below and two small horns above) and the glyph of Sagittarius (♐, a "
        "diagonal arrow pointing up-right with a short crossbar). Palette: Hod orange (#E07B24), electric"
        " white (#FFFFFF), flame red (#D2461E), pale lightning blue (#9AD1F5) and the full rainbow "
        "spectrum in the arch. Light comes from the rods themselves, flickering and bright. The whole "
        "image should feel like Swiftness: energy as a flash of light, news and ideas arriving all at "
        "once."
    ),
    "bastoni-09": (
        "A radiating, perfectly balanced composition of nine wands of Fire in the form of arrows, with no"
        " human figures. Eight slender golden arrows cross each other in a symmetrical star behind, and "
        "in front of them stands one larger central arrow, vertical and dominant. Each arrow has a "
        "crescent Moon at one end and a small blazing Sun disc at the other, arranged so that suns and "
        "moons alternate around the star, the energy flowing between them like a tide. The central arrow "
        "bears a full golden Sun at its top and a silver crescent Moon at its base. Nine tongues of flame"
        " rise around the star in a ninefold ring (an enneagram, a nine-pointed star drawn with straight "
        "lines), drawn precisely and clearly. The background is the deep violet of Yesod (Foundation, the"
        " ninth sephira, the sphere of the Moon, of the astral tides and the vital force that underlies "
        "all things), swirling softly like night water. At the top, drawn precisely and clearly in "
        "silver-white, glow the glyph of the Moon (☽, a crescent open to the left) and the glyph of "
        "Sagittarius (♐, a diagonal arrow pointing up-right with a short crossbar). Palette: deep violet "
        "(#6A3D9A), indigo night (#2B1B4E), silver (#D8D8E8), solar gold (#E6B422) and flame red-orange "
        "(#D2461E). Light pulses from the central arrow, alternating warm solar and cool lunar tones. The"
        " whole image should feel like Strength: health and endurance born from the harmonious "
        "alternation of solar and lunar energy, a force that renews itself."
    ),
    "bastoni-10": (
        "A heavy, compressed composition of ten wands of Fire, with no human figures. Eight ordinary "
        "wands stand upright side by side like the bars of a cage, packed tightly across the width of the"
        " image. Laid across them, forming a great horizontal barrier in front, are two enormous dark-"
        "iron dorjes (vajra thunderbolt-sceptres: a central grip with clawed prongs at each end), "
        "crossing slightly in an X, dominating and locking the eight wands in place. Between the bars, "
        "the flames have turned dim, smoky and reddish-brown, struggling to rise and bent downward, as if"
        " choked; embers fall to the ground below. The ground is a hard, cracked earth. The background is"
        " divided into the four colours of Malkuth (the Kingdom, the tenth sephira, the material world, "
        "the final heaviness of matter): citrine, olive, russet and black, in four muted quarters. In the"
        " upper corners, drawn precisely and clearly in dull lead-grey, appear the glyph of Saturn (♄, a "
        "cross whose lower end curls into a hook like a sickle) and the glyph of Sagittarius (♐, a "
        "diagonal arrow pointing up-right with a short crossbar). Palette: olive-citrine (#9C8A3E), "
        "russet (#7A3B1E), black (#141210), smoky flame red (#D2461E, dulled) and iron grey (#4A4A4A). "
        "The light is low and oppressive, coming weakly from the choked flames, with deep shadows above. "
        "The whole image should feel like Oppression: fire imprisoned by its own excess, force turned "
        "into rigid, exhausting burden."
    ),
    "bastoni-cavaliere": (
        "A dynamic diagonal composition charging from lower left to upper right. In the centre a knight "
        "in full armour of blackened steel inlaid with gold flame patterns rides a powerful black "
        "stallion in mid-leap, forelegs raised, mane streaming like smoke. The knight wears a helmet "
        "crowned with the crest of a winged horse's head (a small horse head with spread wings, "
        "traditional crest of the Knight of Wands), and a scarlet cloak flaring behind him. In his right "
        "hand he holds high a blazing torch-wand, its flame long and horizontal from the speed. The "
        "ground below is a plain of leaping flames that the horse jumps over. In the cloak's flames are "
        "two upward-pointing triangles, one inside the other (the alchemical symbol of Fire, an "
        "equilateral triangle apex up, doubled to mean Fire of Fire), drawn precisely. In the upper sky, "
        "drawn precisely and clearly in gold, glow the glyph of Scorpio (♏, an M-shaped sign whose last "
        "stroke ends in an upward arrow like a sting) and the glyph of Sagittarius (♐, a diagonal arrow "
        "pointing up-right with a short crossbar), marking his span from 21° Scorpio to 20° Sagittarius. "
        "Behind him the grey radiance of Chokmah (Wisdom, the second sephira, pure dynamic masculine "
        "force) spreads as streaks of silver light. Palette: flame orange (#FF7F24), scarlet (#D2461E), "
        "jet black (#0E0E0E), gold (#E6B422) and silver-grey (#9EA2A6). Light blazes from the torch. The "
        "whole image should feel like pure, impetuous fire in its charge, swift, generous and violent."
    ),
    "bastoni-regina": (
        "A calm, stable, vertically centred composition. A queen sits enthroned in the middle ground on a"
        " throne of carved basalt and gold, surrounded by a ring of steady, rippling flames that flow "
        "around her like water. Her eyes are half closed in contemplation, long copper-red hair falls "
        "over a flowing robe of deep blue-green edged with flame embroidery, and over her head rests a "
        "crown bearing a winged disc (a sun disc with outspread wings). In her right hand she holds "
        "upright a thyrsus (a long wand crowned with a pinecone, Dionysian symbol of fertile fire); her "
        "left hand rests on the head of a spotted leopard lying peacefully beside the throne. Her crown "
        "bears a winged leopard's head crest. At her feet, set into the dais, is the alchemical triangle "
        "of Fire (apex up) with the triangle of Water (apex down) inscribed within it, drawn precisely, "
        "showing Water of Fire. Above her, drawn precisely and clearly in soft gold, glow the glyph of "
        "Pisces (♓, two facing crescents joined by a horizontal bar) and the glyph of Aries (♈, two "
        "curved horns joined at the base like a ram's head), marking her span from 21° Pisces to 20° "
        "Aries. The background is the deep darkness of Binah (Understanding, the maternal third sephira)."
        " Palette: steel blue (#4682B4), deep black (#141414), flame red (#D2461E), copper (#B87333) and "
        "gold (#E6B422). Light comes softly from the surrounding fire. The whole image should feel like "
        "fire contained, magnetic, warm and sovereign."
    ),
    "bastoni-principe": (
        "A strong forward-moving composition along a gentle diagonal. A young prince stands in a golden "
        "chariot shaped like a flaming shell, drawn by a powerful maned lion that strides forward through"
        " a sea of flames. The prince wears gold scale armour, and his helmet carries the crest of a "
        "winged lion's head (a lion head with spread wings, the traditional crest of the Prince of "
        "Wands). In his right hand he holds forward a wand crowned with a phoenix (a fiery bird rising "
        "from its own flames, symbol of rebirth); his left hand holds loose reins of flame. Painted on "
        "the chariot's side is the alchemical triangle of Fire (apex up) combined with the triangle of "
        "Air (apex up with a horizontal bar across it), drawn precisely, meaning Air of Fire. High in a "
        "yellow sky, drawn precisely and clearly in gold, appear the glyph of Cancer (♋, two small "
        "circles with tails curving around each other like a 69 on its side) and the glyph of Leo (♌, a "
        "looping line like a lion's mane ending in a curled tail), marking his span from 21° Cancer to "
        "20° Leo. Behind his head shines a solar halo, the gold of Tiphareth (Beauty, the sixth sephira, "
        "the solar heart of the Tree). Palette: khaki gold (#F0E68C), solar yellow (#FFD34E), flame red-"
        "orange (#D2461E), crimson (#A31621) and bronze (#8C6A2F). Bright light comes from the sun behind"
        " him and the flames. The whole image should feel like fire becoming conscious will: swift, "
        "noble, proud and self-renewing."
    ),
    "bastoni-principessa": (
        "A grounded vertical composition. A young, strong princess stands barefoot on dark volcanic earth"
        " in the foreground-centre, her body wrapped in a short, flame-coloured robe that flutters "
        "upward, her feathered headdress of tall plumes echoing the traditional ostrich plumes of the "
        "Princess of Wands. With her right arm she holds aloft a wand crowned by a small radiant sun "
        "disc. A tiger crouches at her left, her hand on its back. On the right stands a small stone "
        "altar decorated with carved ram's heads, on which a fire burns. Flames spring up from the earth "
        "all around her as if the ground itself were igniting, Carved on the altar's front is the "
        "alchemical triangle of Fire (apex up) combined with the triangle of Earth (apex down with a "
        "horizontal bar across it), drawn precisely, meaning Earth of Fire. In the sky above, drawn "
        "precisely and clearly in gold, glow the glyphs of Cancer (♋, two small circles with tails "
        "curving around each other), Leo (♌, a looping line like a lion's mane ending in a curled tail) "
        "and Virgo (♍, an M-shaped sign with a loop crossing its last stroke), the quadrant of heaven she"
        " rules as throne of the Ace. The background reflects Malkuth (the Kingdom, the tenth sephira, "
        "matter), in citrine, olive, russet and black tones. Palette: earthy brown (#8B6F47), russet "
        "(#7A3B1E), flame red-orange (#D2461E), ember gold (#F4B942) and olive (#6B6B2F). Light springs "
        "from below, from the burning ground. The whole image should feel like fire made flesh: daring, "
        "spontaneous and free."
    ),
}
