"""Scene per le immagini delle carte: Coppe (Cups). Una scena per carta, in inglese."""

SCENE = {
    "coppe-01": (
        "A vertical, perfectly symmetrical composition dominated by one enormous primordial chalice of pale "
        "silver and mother-of-pearl, a Holy Grail of superhuman scale at the exact centre. Its stem rests "
        "on a thin upturned crescent moon (a narrow silver sickle with both horns pointing upward) that "
        "floats just above a calm, deep sea in the foreground. From the zenith a single vertical shaft of "
        "pure white brilliance descends into the mouth of the cup: the light of Kether (the first sephira, "
        "the Crown, undivided white radiance before all form). From the brim the water overflows in two "
        "symmetrical transparent curtains that fall slowly back into the sea. The sea surface is covered "
        "with open white and pale blue lotus flowers in rows receding to a low horizon,. Engraved on the "
        "bowl of the chalice, drawn precisely and clearly, is the Hebrew letter He (ה, a horizontal top bar "
        "joined to a right vertical leg, with a short separate left leg: an open doorway), the first He of "
        "the divine name, the Mother who receives. Above the rim hovers the alchemical triangle of Water "
        "(▽, an equilateral triangle pointing downward), drawn cleanly in thin gold line. Palette: "
        "brilliant white #F5F3E7, pearl, silver, deep sea blue #1E6FB0 and soft gold; the light falls "
        "straight down from above and glows back from inside the cup. The whole image should feel like the "
        "first stillness of love before any feeling has taken shape: pure receptivity, a womb of light "
        "waiting to be filled."
    ),
    "coppe-02": (
        "A symmetrical composition built on a vertical axis over a perfectly calm sea. In the middle ground "
        "two slender chalices of polished silver stand side by side on the water, tilted gently toward each "
        "other. Between them a single tall lotus stem rises from the sea and opens into one large "
        "white-and-rose lotus at the centre of the card. Two sleek dolphins, one silver-blue and one pale "
        "gold, leap from the water on either side in mirror-image arcs, their bodies curving up and over so "
        "that their snouts almost touch above the lotus; from their mouths two thin streams of clear water "
        "fall into the two cups, and the overflow of each cup runs across the water into the other, forming "
        "a luminous figure-eight (a lemniscate, the sign of endless exchange) on the sea surface. The "
        "background is the soft grey of Chokmah (the second sephira, Wisdom, the starry sphere of the "
        "primal masculine force), scattered with faint pale stars. High in the sky, drawn precisely and "
        "clearly, are the glyph of Venus (♀, a circle above a small equal-armed cross) and the glyph of "
        "Cancer (♋, two small circles each with a curved tail, one above the other, like a sideways 69), "
        "marking Venus in Cancer, the first decan of Cancer. Palette: pearl grey #8A8D8F, silver, soft "
        "rose, pale gold, sea blue #1E6FB0; a gentle dawn light comes from behind the lotus. The whole "
        "image should feel like love as harmony of two polarities recognising and completing each other."
    ),
    "coppe-03": (
        "A night scene under the deep black vault of Binah (the third sephira, Understanding, the dark "
        "Great Mother, Saturnine and fertile), composed as a downward-pointing triangle, the triangle of "
        "Water (▽). Three chalices shaped like ripe pomegranates, their bowls a deep crimson-gold with a "
        "small crown-shaped rim like the calyx of the fruit, are placed at the three corners of this "
        "triangle: two high on the left and right, one low in the centre. Each rests on a curving green "
        "stem that rises from a single lotus plant floating on a dark, still sea in the foreground. The "
        "cups are overflowing: water spills from the two upper cups in shining ribbons into the lower cup, "
        "and from it into the sea, so that the whole triangle is a cascading fountain. Split pomegranates "
        "lie open among the lotus leaves, showing glistening ruby seeds, the sweet fruit of Persephone that "
        "binds one to the underworld. Drawn precisely and clearly in silver in the upper corners are the "
        "glyph of Mercury (☿, a circle with a small cross below and two small horns above) and the glyph of "
        "Cancer (♋, two small circles with curved tails, one above the other, like a sideways 69), for "
        "Mercury in Cancer, the second decan. Palette: black #1A1A1A, midnight indigo, pomegranate crimson, "
        "gold, sea blue #1E6FB0; the light seems to come from within the overflowing water itself. The "
        "whole image should feel like fertile, shared joy that is generous yet quietly asks to be honoured "
        "and not taken for granted."
    ),
    "coppe-04": (
        "A solid, stable composition built on a square. In the centre a massive square pedestal of "
        "blue-veined marble, carved with a simple meander border, rises from a restless sea whose grey-blue "
        "waves break and foam against its base in the foreground. On its flat top stand four heavy, ornate "
        "chalices of gold set with sapphires, one at each corner of the square, wide-bowled and brimming, "
        "their surfaces smooth and almost motionless. From a single lotus in the centre of the pedestal "
        "four stems curve outward, one to each cup, their flowers bending down and letting water trickle "
        "slowly into the bowls; the flow is thin and lazy, and a faint film lies on the surface of the "
        "water, hinting at stagnation. A fold of embroidered blue velvet drapes one side of the pedestal. "
        "The background is the deep blue of Chesed (the fourth sephira, Mercy, the benevolent, expansive, "
        "Jupiterian order that builds and preserves), with a calm sky above the troubled sea. A large "
        "silver crescent moon (☽, a thin curved sickle) hangs above the square, and beside it, drawn "
        "precisely and clearly, the glyph of Cancer (♋, two small circles with curved tails, one above the "
        "other, like a sideways 69), for the Moon in Cancer, the third decan. Palette: royal blue #1F4E9A, "
        "sapphire, gold, marble white, violet shadows, sea blue #1E6FB0; a soft, even moonlight from above. "
        "The whole image should feel like pleasure settled into luxury: comfortable, secure, and already on "
        "the edge of stillness."
    ),
    "coppe-05": (
        "A harsh, dry composition under a blood-red sky. Five empty chalices of tarnished bronze stand on "
        "the five points of an inverted pentagram (a five-pointed star with one point downward, the sign of "
        "matter overthrowing spirit), traced in thin cracked lines of dull red across the ground of the "
        "middle distance. The cups are hollow and dry: one is cracked down its side, one tilts as if about "
        "to fall. The sea that once fed them has evaporated into a flat, cracked salt pan scattered with "
        "white crystals and a few dead shells in the foreground. From a single withered root in the centre "
        "of the star, five brittle lotus stems rise and twist like thorny wire, each ending in a dead, "
        "brown, drooping flower that hangs above a cup without giving a drop. The atmosphere is the fierce "
        "scarlet of Geburah (the fifth sephira, Severity, the martial force that burns away and purifies). "
        "Drawn precisely and clearly at the top of the card, glowing like embers, are the glyph of Mars (♂, "
        "a circle with an arrow pointing up-right) and the glyph of Scorpio (♏, like a letter m whose last "
        "stroke ends in an upward arrow-tipped tail), for Mars in Scorpio, the first decan. Palette: "
        "scarlet #C8102E, rust, ash grey, bleached salt white, dull bronze, with only a distant thin strip "
        "of faded sea blue #1E6FB0 on the horizon; light is a glaring, shadowless heat. The whole image "
        "should feel like the moment an illusion collapses and love dries up, a painful but purifying loss."
    ),
    "coppe-06": (
        "A radiant, balanced composition built on a hexagram (two interlaced equilateral triangles, one "
        "pointing up and one down, the sign of perfect harmony). Six golden chalices, graceful and slender, "
        "stand at the six points of this star, which floats above a sunlit sea in the foreground. From the "
        "centre of the hexagram a cluster of copper-green stems rises and branches out, and at the end of "
        "each stem a warm orange-gold lotus bends over one cup, pouring a single steady stream of clear "
        "water into it; each cup is filled exactly to the brim and not a drop spills, a picture of measure. "
        "Behind the star a great golden sun disk rises from the sea, its rays forming a halo around the "
        "whole design: the splendour of Tiphareth (the sixth sephira, Beauty, the harmonious solar heart of "
        "the Tree of Life). Beneath the calm surface of the sea, faintly visible, dark depths hint at "
        "Scorpio's hidden waters warmed by the sun. Drawn precisely and clearly in gold at the top are the "
        "glyph of the Sun (☉, a circle with a dot at its centre) and the glyph of Scorpio (♏, like a letter "
        "m whose last stroke ends in an upward arrow-tipped tail), for the Sun in Scorpio, the second "
        "decan. Palette: warm gold #E6B422, amber, soft orange, rose, copper green, luminous sea blue "
        "#1E6FB0; the light comes from the rising sun behind the centre. The whole image should feel like "
        "pleasure in its perfect measure: healthy, fertile, sensual joy in balance."
    ),
    "coppe-07": (
        "An oppressive, sagging composition in which everything slides downward. Seven chalices of "
        "iridescent glass, shimmering with oily rainbow sheens of green, purple and bronze, are arranged in "
        "a descending zigzag cascade from the upper left to the lower right, each tilted so that it spills "
        "into the next; the lowest and largest cup overflows into a stagnant swamp that fills the "
        "foreground. What pours is not clear water but a thick, viscous, slimy green liquid that clings to "
        "the rims in long drips. The lotus flowers that should feed the cups have mutated into poisonous "
        "tiger lilies, orange with dark spots and curling tongues, hanging on limp stems. The swamp surface "
        "is covered in scum and floating petals, with faint bubbles and a low mist. The background is a "
        "sickly, murky version of the emerald of Netzach (the seventh sephira, Victory, the realm of "
        "desire, feeling and Venus), here corrupted and clouded. Drawn precisely and clearly, but "
        "half-veiled by the mist near the top, are the glyph of Venus (♀, a circle above a small "
        "equal-armed cross) and the glyph of Scorpio (♏, like a letter m whose last stroke ends in an "
        "upward arrow-tipped tail), for Venus in Scorpio, the third decan, Venus in her sign of detriment. "
        "Palette: murky emerald #2E8B57, bilious yellow-green, bruised purple, oily bronze, with muddied "
        "sea blue #1E6FB0 in the depths; the light is dim and greenish, filtering sideways through fog. The "
        "whole image should feel like seductive excess turning to poison, pleasure rotting in illusion and "
        "self-deception."
    ),
    "coppe-08": (
        "A heavy, still composition under a low leaden sky. Eight shallow chalices of dull pewter, some "
        "chipped and cracked, stand in two uneven rows of four across the middle ground on a flat, murky "
        "pool that fills the foreground; several stand slightly askew. Above them, drooping lotus stems "
        "bend almost to the water, their flowers faded and sagging, letting only a few slow drops fall into "
        "a few of the cups while the others stay nearly empty. The water of the pool is opaque, brownish "
        "and motionless, with no current and no reflection of light. In the distance, pale ghostly hills "
        "dissolve into grey haze. A faint octagonal pattern (an eight-sided figure, the geometry of Hod) is "
        "traced in dim orange lines on the surface of the pool around the cups, like a forgotten structure "
        "of thought. The muted orange of Hod (the eighth sephira, Splendour, the realm of intellect and "
        "Mercury) glows only weakly through the clouds. Drawn precisely and clearly in dark grey at the top "
        "are the glyph of Saturn (♄, a small cross whose lower stroke curves into a hooked tail, like a "
        "letter h with a crossbar) and the glyph of Pisces (♓, two outward-facing arcs joined by a "
        "horizontal bar), for Saturn in Pisces, the first decan. Palette: dull orange #E07B24, leaden grey, "
        "olive brown, pewter, and a clouded sea blue #1E6FB0; flat, diffuse light without shadows. The "
        "whole image should feel like exhausted emotion, water that no longer flows, a feeling gone "
        "stagnant."
    ),
    "coppe-09": (
        "A serene, orderly composition built on a perfect square. Nine gleaming chalices of silver and "
        "amethyst stand in a grid of three rows of three, arranged like a tiered fountain rising from a "
        "calm violet sea in the foreground: the top row stands highest, the bottom row lowest. Above the "
        "top row a canopy of nine lotus flowers on gracefully curving stems pours clear water into each "
        "cup; every cup overflows gently into the one below, and the bottom row spills in nine shining "
        "threads into the sea, so the whole square seems alive with steady, abundant flow. Behind the "
        "fountain a large full moon rises, pale silver-violet, for Yesod (the ninth sephira, the "
        "Foundation, lunar, the stable base where all the forces above gather before manifesting). Its "
        "light is reflected in every cup like nine small moons. Fine concentric circles on the water spread "
        "from each falling thread. Drawn precisely and clearly in gold in the upper part of the sky are the "
        "glyph of Jupiter (♃, like the number 4 with a curved left stroke) and the glyph of Pisces (♓, two "
        "outward-facing arcs joined by a horizontal bar), for Jupiter in Pisces, the second decan, Jupiter "
        "in his own house. Palette: deep violet #6A3D9A, lavender, amethyst, silver, pale gold, sea blue "
        "#1E6FB0; soft moonlight from behind, mixed with a warm glow from the water. The whole image should "
        "feel like complete, well-founded happiness: the wish fulfilled, calm, generous and radiating "
        "outward."
    ),
    "coppe-10": (
        "A tall, structured composition in which ten chalices are arranged on the ten positions of the "
        "Kabbalistic Tree of Life (three vertical columns of circles, left, middle and right, linked by "
        "thin glowing lines into a single diagram), set against a warm, wine-red sky above a heavy sea. The "
        "cups are ornate, of red-gold enamel, each resting on a small sphere of light marking its sephira. "
        "From the topmost cup, which leans noticeably forward on its axis, water spills and runs downward "
        "through the channels of the Tree, filling each cup in turn until the lowest cup, at the base of "
        "the central column, is brimming over into the sea. A great lotus behind the diagram has opened "
        "fully and begun to shed its petals, drifting down like slow red rain. The lowest cup stands on a "
        "disk divided into four quarters coloured citrine, olive, russet and black: the colours of Malkuth "
        "(the tenth sephira, the Kingdom, the material world where all forces come to rest). Drawn "
        "precisely and clearly in bright crimson at the top of the card are the glyph of Mars (♂, a circle "
        "with an arrow pointing up-right) and the glyph of Pisces (♓, two outward-facing arcs joined by a "
        "horizontal bar), for Mars in Pisces, the third decan. Palette: wine red, crimson, red-gold, "
        "olive-citrine #9C8A3E, russet, and deep sea blue #1E6FB0; heavy late-afternoon light from the "
        "upper left. The whole image should feel like fulfilment that is already overfull, a completeness "
        "about to tip over into change."
    ),
    "coppe-cavaliere": (
        "A dynamic diagonal composition sweeping from lower left to upper right. A winged knight rides a "
        "powerful white horse that leaps forward over the crests of storm-bright waves, its forelegs "
        "raised. The knight wears close-fitting armour of silver-green scales like a fish, with large "
        "translucent wings of pale blue and white rising from his shoulders; his helmet is crowned with the "
        "crest of a peacock with its tail fanned open, iridescent blue, green and gold. In his outstretched "
        "right hand he holds high a golden chalice from which a small red crab climbs out over the rim. "
        "Behind him, a curtain of falling rain catches the light. Hovering in the sky before him, drawn "
        "precisely and clearly, is the Hebrew letter Yod (י, a small comma-like flame stroke), the fiery "
        "first letter of the divine name, beside the combined sign of Fire of Water (an upward fire "
        "triangle △ set inside a downward water triangle ▽). Along the upper edge, also precise and clear, "
        "are the glyph of Aquarius (♒, two parallel zigzag wave lines) and the glyph of Pisces (♓, two "
        "outward-facing arcs joined by a horizontal bar), marking his span from 21 degrees Aquarius to 20 "
        "degrees Pisces. The sky has the silvery grey of Chokmah (the second sephira, Wisdom, the dynamic "
        "starry force). Palette: bright orange #FF7F24 in the sunlit edges of the clouds, white, silver, "
        "peacock blue and green, sea blue #1E6FB0; strong light from the upper right. The whole image "
        "should feel like idealistic, romantic passion rushing forward, the fire that sets the waters "
        "moving."
    ),
    "coppe-regina": (
        "A still, vertically symmetrical composition centred on a queen enthroned on a mirror-calm lake "
        "that fills the whole lower half of the card. Her throne is a tall, pale scallop shell of "
        "mother-of-pearl rising straight from the water. She is almost translucent, veiled from head to "
        "foot in layered curtains of shimmering light and fine white gauze, so that her face and body are "
        "only glimpsed, serene and inward. Her crown bears the crest of an ibis with long curved beak and "
        "outstretched wings. In her right hand she holds a clear crystal chalice from which a small "
        "crayfish emerges; in her left, a single long-stemmed blue lotus. A white ibis stands in the "
        "shallows at her feet. The lake reflects her with perfect fidelity, so that the reflection below is "
        "as bright as the figure above. Drawn precisely and clearly on the water are the Hebrew letter He "
        "(ה, a top bar with a right vertical leg and a short separate left leg), and the doubled sign of "
        "Water of Water (two downward triangles ▽ ▽). High above, fine and clear, are the glyph of Gemini "
        "(♊, two vertical strokes joined by curved bars at top and bottom) and the glyph of Cancer (♋, two "
        "small circles with curved tails, like a sideways 69), for her span from 21 degrees Gemini to 20 "
        "degrees Cancer. The deep sky carries the dark, maternal indigo-black of Binah (the third sephira, "
        "Understanding, the Great Mother). Palette: steel blue #4682B4, pearl, silver, pale lilac, sea blue "
        "#1E6FB0; soft diffused light that seems to come from the water. The whole image should feel like "
        "pure receptivity: a perfect mirror that reflects without distortion."
    ),
    "coppe-principe": (
        "A gliding, horizontal composition across placid water veiled in rising mist. A young prince stands "
        "upright in a light shell-shaped chariot of silver and pale gold that skims over the surface, drawn "
        "by a great eagle with broad wings spread wide, pulling it by fine golden reins. The prince wears "
        "flowing armour of lightweight silver scales with a cloak of sea-green feathers, and his helmet "
        "bears the crest of an eagle with wings raised. His face is calm and composed, masking intensity. "
        "In his right hand he holds a golden chalice from which a green serpent coils upward, head poised; "
        "in his left, a single open lotus with its flower turned downward toward the water. Veils of vapour "
        "rise from the water all around, water becoming air. Drawn precisely and clearly in the mist ahead "
        "of the eagle is the Hebrew letter Vau (ו, a simple vertical stroke with a small hook at the top, "
        "like a nail), the third letter of the divine name, beside the sign of Air of Water (an upward "
        "triangle crossed by a horizontal bar, set inside a downward water triangle ▽). Along the top, fine "
        "and clear, are the glyph of Libra (♎, a short horizontal line beneath a line with a rounded hump "
        "in its middle) and the glyph of Scorpio (♏, like a letter m with an upward arrow-tipped tail), for "
        "his span from 21 degrees Libra to 20 degrees Scorpio. A golden sun glow of Tiphareth (the sixth "
        "sephira, Beauty, the harmonious heart) lights the mist from behind. Palette: pale khaki gold "
        "#F0E68C, silver, sea green, grey mist, sea blue #1E6FB0; soft backlight. The whole image should "
        "feel like secret passion under a surface of calm control."
    ),
    "coppe-principessa": (
        "A grounded, graceful composition in which a young princess stands barefoot on a low rock at the "
        "edge of the sea, waves breaking softly around her ankles, poised as if to begin a slow dance. She "
        "wears a long flowing gown of pale sea-green and white, decorated with crystalline patterns like "
        "frost and salt. Her crown bears the crest of a white swan with wings open. In her right hand she "
        "holds up a large spiral seashell, from whose opening a small turtle emerges, and a playful dolphin "
        "arches out of the water beside her, curling around her left side. A few lotus flowers float in the "
        "shallows. Drawn precisely and clearly on the rock beside her is the Hebrew letter He (ה, a top bar "
        "with a right vertical leg and a short separate left leg), the final He of the divine name, beside "
        "the sign of Earth of Water (a downward triangle crossed by a horizontal bar, inside a downward "
        "water triangle ▽). Across the sky, fine and clear, are the glyphs of Libra (♎, a line beneath a "
        "line with a rounded hump), Scorpio (♏, like a letter m with an upward arrow-tipped tail) and "
        "Sagittarius (♐, an arrow pointing up-right with a short crossbar on its shaft), the quadrant of "
        "heaven she rules as throne of the Ace of Cups. The rock and shore carry the four colours of "
        "Malkuth (the tenth sephira, the Kingdom, the material world): citrine, olive, russet and black. "
        "Palette: warm earth brown #8B6F47, sea green, pearl white, soft pink, sea blue #1E6FB0; gentle "
        "morning light from the left. The whole image should feel like tender imagination taking shape, "
        "water crystallising into a living form."
    ),
}
