"""Scene per le immagini delle carte: Spade (Swords). Una scena per carta, in inglese."""

SCENE = {
    "spade-01": (
        "A single colossal sword stands vertically on the central axis, point upward, rising out of a "
        "churning sea of pale grey clouds in the lower third and piercing into a vast open sky; the whole"
        " composition is a strict vertical symmetry, a line of pure force splitting the air. The sword is"
        " immense and primordial, far larger than any human scale: a straight double-edged blade of "
        "polished silver-white steel with a faint mirror sheen, the crossguard shaped as two outspread "
        "feathered wings, the grip wound with gold wire, the pommel a crescent moon cradling a small sun "
        "disk. Down the centre of the blade the Greek word ΘΕΛΗΜΑ (THELEMA, meaning 'Will') is engraved "
        "in clear, precise capital letters. The tip enters a radiant crown of light made of exactly "
        "twenty-two sharp golden rays (the twenty-two paths of the Tree of Life), and above it a small "
        "white point of brilliance marks Kether (the first sephira, the Crown, pure undivided light). "
        "Around the blade the clouds are being torn open in a spiral, parting like curtains, with thin "
        "currents of wind drawn as fine silver lines. Near the hilt, drawn precisely and clearly, floats "
        "the alchemical sign of Air (🜁, an upward-pointing triangle crossed by a horizontal bar). "
        "Palette: brilliant white #F5F3E7, pale gold #D9C23A, cool silver, soft pearl-grey and a clear "
        "high sky of palest blue; light pours down from the crown above, dazzling and cold. The whole "
        "image should feel like the first flash of an idea cutting through fog: clarity, invocation and "
        "the intellect lit by Will."
    ),
    "spade-02": (
        "A calm, perfectly balanced symmetrical composition: two long ornate swords cross at the exact "
        "centre of the image, their blades forming a wide X with points upward, hilts resting low on "
        "either side like the two pans of a scale. Where the blades cross they are bound together by a "
        "single open five-petalled rose of soft sky-blue, luminous and serene, its petals just touching "
        "both edges without being cut. The two swords are twins yet mirror-opposite: the left hilt is "
        "silver with a crescent-moon pommel, the right hilt is pale gold with a small balance-beam guard."
        " Behind them the background is a quiet geometric lattice of interlocking grey pinwheel shapes "
        "and thin concentric rings, like a woven pattern of stilled wind, spreading evenly to the edges. "
        "Above the rose, drawn precisely and clearly, hang the astrological glyphs of the Moon (☽, a thin"
        " crescent) and Libra (♎, a short horizontal line beneath a line with a rounded hump, like the "
        "sun setting on a horizon), side by side, for the Moon in Libra. Behind the crossing point a soft"
        " grey disk suggests Chokmah (the second sephira, Wisdom, the pure dynamic force of the Father, "
        "colour grey). Palette: dove grey #8A8D8F, pearl, silver, pale gold #D9C23A and clear sky-blue "
        "#7FB3D5 for the rose; the light is soft, even and diffused, like moonlight on still air, with no"
        " shadows. The whole image should feel like a held breath after a quarrel: peace born from the "
        "balanced tension of opposites."
    ),
    "spade-03": (
        "A dark, stormy composition centred on a wounded flower. In the middle floats a large yellow "
        "rose, its petals splitting apart and drifting outward in fragments. Two curved sabres, like "
        "crescent moons, bend in from the left and right, their tips meeting at the heart of the rose; a "
        "third sword, long, straight and heavy, descends vertically from the top of the image and strikes"
        " exactly at that meeting point, so the three blades form a downward-pointing triangle converging"
        " on the broken bloom. The hilts are sombre: blackened iron, lead-grey leather grips, sober "
        "crossguards with no jewels. Behind them the background is a deep black-violet sky filled with "
        "heavy storm clouds and slanting grey rain, with faint pale lightning far away. Above, drawn "
        "precisely and clearly, the astrological glyphs of Saturn (♄, a small cross whose lower arm curls"
        " into a sickle-like hook) and Libra (♎, a short horizontal line beneath a line with a rounded "
        "hump), for Saturn in Libra. A barely visible great black disk behind the whole scene evokes "
        "Binah (the third sephira, Understanding, the dark Great Mother, Saturnine, whose colour is "
        "black), like a womb of night. Palette: near-black #1A1A1A, charcoal, slate blue, cold rain-grey,"
        " and the yellow of the rose #E8C547 fading to dull ochre where it breaks, with pale gold #D9C23A"
        " on the blade edges; a thin cold light falls from above onto the rose alone. The whole image "
        "should feel like a cosmic, maternal sorrow: grief that is finally understood rather than denied."
    ),
    "spade-04": (
        "A stable, orderly composition with fourfold symmetry. Four identical swords are arranged "
        "diagonally, their points converging inward to the centre so that together they form a saltire "
        "(an X-shaped cross, the cross of Saint Andrew). At the centre, where the four points meet "
        "without touching, blooms a large flat rose of many petals arranged in seven rings of seven "
        "(forty-nine petals), soft rose-pink and cream, like a mandala that holds the blades at rest. The"
        " hilts sit in the four corners of the image, each one ornate and ceremonial, with blue enamel, "
        "gold filigree and a small square pommel, as if the swords had been laid down by treaty. Behind "
        "them is a background of calm geometric panels, a square grid of deep-blue tiles softly divided "
        "like the floor of a council hall. In the upper area, drawn precisely and clearly, the "
        "astrological glyphs of Jupiter (♃, a figure like a stylised number 4 with a curved left arm) and"
        " Libra (♎, a short horizontal line beneath a line with a rounded hump), for Jupiter in Libra. A "
        "large faint blue disk behind the rose evokes Chesed (the fourth sephira, Mercy, the benevolent "
        "ordering rule of Jupiter, colour blue). Palette: royal blue #1F4E9A, deep ultramarine, cream, "
        "soft rose-pink, polished steel and pale gold #D9C23A; light is steady and warm, coming evenly "
        "from the front as if from a quiet hall. The whole image should feel like a truce and a pause for"
        " recovery: conflict contained by order and agreement."
    ),
    "spade-05": (
        "A broken, uneasy composition. Five swords are arranged so that their blades trace an inverted "
        "pentagram (a five-pointed star with one point downward), but the figure is distorted and "
        "imperfect: the blades are bent, notched and of unequal length, and their hilts are all "
        "different, one with a cracked jewel, one with a snapped guard, one wrapped in fraying cord, one "
        "rusted, one missing its pommel. Petals from a pale pink rose fall away from the centre of the "
        "star, drifting down and scattering on the lower edge, some already wilting. The background is a "
        "turbulent crimson sky split by jagged diagonal streaks of wind, like a battlefield of air after "
        "the fight, with a few torn banners of cloud. Near the top, drawn precisely and clearly, the "
        "astrological glyphs of Venus (♀, a circle above a small cross) and Aquarius (♒, two parallel "
        "horizontal zigzag lines like waves), for Venus in Aquarius, the gentle planet weak in a cold "
        "sign. Behind the star a dim red pentagonal disk evokes Geburah (the fifth sephira, Severity, the"
        " martial force of judgement, colour scarlet), fractured by a hairline crack. Palette: scarlet "
        "#C8102E, dark oxblood, ash grey, tarnished steel, fading rose-pink and a few touches of pale "
        "gold #D9C23A; light comes low and harsh from the lower left, casting sharp uneven shadows. The "
        "whole image should feel like a defeat of the mind: an order that has come apart because the will"
        " to fight was too soft."
    ),
    "spade-06": (
        "A harmonious, radiant composition of perfect sixfold symmetry. Six slender, identical swords are"
        " arranged like the spokes of a wheel: their hilts sit on the outer ring and together trace a "
        "hexagram (a six-pointed star made of two interlaced triangles, one pointing up and one pointing "
        "down), while their points converge toward the centre. At the centre stands a small golden "
        "equal-armed cross, and on its heart blooms a red rose of six petals, which all six sword-points "
        "touch lightly and precisely. The hilts are elegant and scientific in feeling, with polished "
        "brass guards engraved with fine measurement marks, like instruments. Behind the design, a "
        "background of thin concentric circles, fine geometric construction lines and compass arcs in "
        "pale gold on sunny yellow suggests a diagram of knowledge. Above, drawn precisely and clearly, "
        "the astrological glyphs of Mercury (☿, a circle with a small crescent on top and a cross below) "
        "and Aquarius (♒, two parallel horizontal zigzag lines like waves), for Mercury in Aquarius. A "
        "glowing golden disk behind the rose evokes Tiphareth (the sixth sephira, Beauty, the harmonious "
        "solar heart of the Tree, colour golden yellow). Palette: golden yellow #E6B422, soft amber, pale"
        " gold #D9C23A, clear sky-blue, polished silver and one rich rose-red #B22234; light radiates "
        "evenly outward from the centre, bright and clear. The whole image should feel like the mind in "
        "balance: objective intelligence reaching a lucid synthesis, method leading to calm."
    ),
    "spade-07": (
        "An unbalanced, tense composition. In the centre a single large sword stands upright, point up, "
        "broad and heavy, with a hilt of emerald-green enamel and gold. Arranged around it in a crescent,"
        " like a waning moon opening upward, are six smaller swords, each with a differently shaped hilt,"
        " their points all aimed at the great blade from both sides, touching it and nicking its edges, "
        "as if wearing it down with many small blows. Nothing is broken yet, but the large blade is "
        "dulled and scratched where the others press. The background is a restless sky of dim sea-green "
        "haze shot with pale streaks of wind that move in contrary directions, and a thin crescent of "
        "cloud mirrors the arc of the small swords. Near the top, drawn precisely and clearly, the "
        "astrological glyphs of the Moon (☽, a thin crescent) and Aquarius (♒, two parallel horizontal "
        "zigzag lines like waves), for the Moon in Aquarius. A faint green disk behind the central hilt "
        "evokes Netzach (the seventh sephira, Victory, the sphere of Venus and of feeling, colour emerald"
        " green), here unstable and wavering in the element of Air. Palette: emerald #2E8B57, murky "
        "sea-green, moonlit silver, tarnished bronze, and pale gold #D9C23A on the central hilt; the "
        "light is weak and shifting, like cold moonlight through moving cloud. The whole image should "
        "feel like futility: a strength worn away by many petty efforts and half-hearted compromises."
    ),
    "spade-08": (
        "A crowded, obstructed composition. Two long, straight swords stand vertically and parallel near "
        "the centre, points upward, like the two pillars of a gate, their blades clean and bright. Across"
        " them, at many different angles, six shorter blades of mismatched cultures and shapes are thrust"
        " in, interrupting the space between the two long swords: a curved scimitar, a wavy kris dagger, "
        "a short Roman gladius, a Japanese-style tanto, a broad machete, a thin rapier, each with its own"
        " foreign-looking hilt. They cross and block one another like a tangled fence. The background is "
        "an orange-amber sky criss-crossed by fine jagged lines like static and small whirling eddies of "
        "wind, as if the air itself were full of noise. In the upper area, drawn precisely and clearly, "
        "the astrological glyphs of Jupiter (♃, a figure like a stylised number 4 with a curved left arm)"
        " and Gemini (♊, like the Roman numeral II with curved bars at top and bottom), for Jupiter in "
        "Gemini. A faint orange disk behind the two long swords evokes Hod (the eighth sephira, "
        "Splendour, the sphere of Mercury and of the analytic intellect, colour orange). Palette: orange "
        "#E07B24, burnt amber, copper, dusty ochre, steel grey and pale gold #D9C23A; the light is "
        "scattered and flickering, coming from several directions at once. The whole image should feel "
        "like interference: a clear purpose hampered by too many distractions, scruples and outside "
        "voices."
    ),
    "spade-09": (
        "A dark, oppressive composition. Nine swords of different lengths hang vertically, points "
        "downward, in a loose descending curtain across the image, their tips at irregular heights near "
        "the lower third. The blades are jagged, serrated like saws, pitted and streaked with rust, and "
        "from their points slow drops of dark violet venom fall toward the bottom edge, where they gather"
        " into a murky pool (no blood, no bodies). The hilts at the top are crude and heavy, black iron "
        "with hooked guards. The background is a deep night of purple and indigo, with a thin pale "
        "crescent moon half hidden and faint shapes of fear in the mist, only suggested. In the upper "
        "area, drawn precisely and clearly, the astrological glyphs of Mars (♂, a circle with an arrow "
        "pointing up-right) and Gemini (♊, like the Roman numeral II with curved bars at top and bottom),"
        " for Mars in Gemini. A dim violet disk behind the curtain of blades evokes Yesod (the ninth "
        "sephira, the Foundation, the lunar sphere of dreams, instinct and the subconscious, colour "
        "violet), here turned into a place of nightmares. Palette: deep violet #6A3D9A, indigo, bruised "
        "plum, rust-brown, blackened steel, sickly green-violet for the venom, and only a trace of pale "
        "gold #D9C23A on the hilts; light is scarce, a cold sickly glow from below. The whole image "
        "should feel like cruelty and sleepless anguish: the intellect sunk into obsessive fear and "
        "instinctive malice."
    ),
    "spade-10": (
        "A shattered yet geometrically ordered composition. Ten swords are placed so that their hilts "
        "occupy the ten positions of the Kabbalistic Tree of Life (ten circles in three vertical columns,"
        " joined by lines): three hilts at the top, then pairs down the sides, one in the middle, one "
        "lower, one at the very bottom. Faint lines connect the hilts like the paths of the Tree. All the"
        " blades point inward toward the central position of the heart, and the sword at the centre is "
        "snapped into pieces, its fragments flying outward, broken by the pressure of the other nine. The"
        " hilts are varied and ruined: cracked, bent, chipped. The background is a burning blood-red and "
        "rust sky, low and heavy, with dark smoke and the pale disk of a dying sun near the horizon. Near"
        " the bottom, drawn precisely and clearly, the astrological glyphs of the Sun (☉, a circle with a"
        " dot at its centre) and Gemini (♊, like the Roman numeral II with curved bars at top and "
        "bottom), for the Sun in Gemini. The lowest hilt rests on a disk divided into four quarters of "
        "citrine, olive, russet and black, evoking Malkuth (the tenth sephira, the Kingdom, the material "
        "world where the descent ends). Palette: dark red #8B1A1A, rust, olive-citrine #9C8A3E, russet, "
        "soot-black and tarnished pale gold #D9C23A; light is a dull red glare from the horizon, dramatic"
        " and final. The whole image should feel like ruin: a structure of thought collapsing completely,"
        " leaving space only to rebuild."
    ),
    "spade-cavaliere": (
        "A dynamic diagonal composition charging from upper right to lower left. An armoured knight rides"
        " a powerful dark-brown horse that dives forward through the sky at full gallop, its legs "
        "stretched, mane and tail streaming like flames of wind, hooves barely touching a torrent of "
        "racing clouds. The knight wears close-fitting silver-grey armour with sharp, wing-like plates, a"
        " flowing orange cloak snapping behind, and a helmet crowned with a winged hexagram (a "
        "six-pointed star with small spread wings, the traditional crest of this knight). In his right "
        "hand he thrusts a long straight sword forward, in his left a short dagger held low, both aimed "
        "along the line of attack. Around him a flock of swallows dives in the same direction, sharp dark"
        " silhouettes. As the Fire of Air, the knight is the swift attack of thought: faint flame-like "
        "tongues edge the wind currents, and in the corner, drawn precisely and clearly, the alchemical "
        "signs of Fire (🜂, an upward triangle) and Air (🜁, an upward triangle crossed by a horizontal "
        "bar). Along the top, drawn precisely and clearly, the zodiac glyphs of Taurus (♉, a circle with "
        "curved horns) and Gemini (♊, like the Roman numeral II with curved bars), for his span from late"
        " Taurus to Gemini. Palette: flame orange #FF7F24, steel grey, pale sky-blue, brown, white cloud "
        "and pale gold #D9C23A; strong light strikes from behind, from the upper right, like sun through "
        "a storm. The whole image should feel like a sudden idea bursting in: fast, fierce, decisive."
    ),
    "spade-regina": (
        "A calm, vertical, enthroned composition. A queen sits on a throne carved from pale cumulus "
        "clouds, high above a sea of lower clouds, her gaze level, lucid and unsentimental. She wears a "
        "flowing gown of steel-blue and silver, layered like feathers of mist. On her head rests a helmet"
        " whose crest is the winged head of a child (a small serene child's face with spread wings), "
        "traditional crest of this queen. In her raised right hand she holds a straight sword upright, "
        "clean and shining; in her lowered left hand she holds by its hair a pale, bloodless mask of a "
        "bearded man, like cracked marble, representing an illusion she has just cut away (no blood, no "
        "gore). As the Water of Air, she is the receptive, reflecting mind: a still circular pool of "
        "clear air hovers at her feet like a mirror, reflecting her sword, and in the corner, drawn "
        "precisely and clearly, the alchemical signs of Water (🜄, a downward triangle) and Air (🜁, an "
        "upward triangle crossed by a horizontal bar). Along the top, drawn precisely and clearly, the "
        "zodiac glyphs of Virgo (♍, like a letter m with a looped final stroke) and Libra (♎, a short "
        "line beneath a line with a rounded hump), for her span from late Virgo to Libra. Palette: steel "
        "blue #4682B4, silver, pearl white, cool lavender-grey and pale gold #D9C23A; clear cold light "
        "falls from above, crystalline and serene. The whole image should feel like lucid perception: "
        "truth seen without illusion, severe but liberating."
    ),
    "spade-principe": (
        "A restless composition built on a strong forward diagonal and many conflicting lines. A young "
        "prince rides in a light, open chariot of silver and pale gold that seems to float on wind rather"
        " than ground, its wheels made of spinning spirals of air. The chariot is drawn by several small "
        "winged child-like sprites (tasteful, clothed in pale tunics), each flying in a different "
        "direction, their harness ropes pulling at odd angles, so the chariot lurches. The prince is "
        "slender and intense, clad in yellow-green armour with feather-like plates, his helmet crested "
        "with a winged angel's head bearing a small pentagram on its brow (a five-pointed star, "
        "traditional crest of this prince). In his right hand he raises a sword to create, in his left he"
        " holds a curved sickle to destroy. Around him swirl thin geometric figures, half-drawn diagrams "
        "and floating ribbons of thought. As the Air of Air, he is pure intellect: in the corner, drawn "
        "precisely and clearly, two alchemical signs of Air (🜁, an upward triangle crossed by a "
        "horizontal bar). Along the top, drawn precisely and clearly, the zodiac glyphs of Capricorn (♑, "
        "like a letter V joined to a looped tail) and Aquarius (♒, two parallel horizontal zigzag lines),"
        " for his span from late Capricorn to Aquarius. Palette: pale khaki-yellow #F0E68C, sky-blue, "
        "emerald-green, silver, white and pale gold #D9C23A; the light is bright and shifting, with many "
        "small highlights. The whole image should feel like a brilliant mind full of ideas that cannot "
        "rest or settle on one direction."
    ),
    "spade-principessa": (
        "A grounded, vertical composition. A young warrior-maiden, Athena-like, stands firmly with feet "
        "planted on a rocky earthen ledge as she drives a straight sword downward before a bare stone "
        "altar. She is armed and helmeted: a close bronze-coloured helmet whose crest is the head of "
        "Medusa with serpents for hair (traditional crest of this princess), a short tunic of russet and "
        "olive under a leather cuirass, a grey cloak whipped sideways by the wind. Her expression is "
        "alert, vigilant and resolute. Around her, a violent storm fills the sky: dark roiling clouds, "
        "gusts drawn as sweeping lines, a few ragged gaps of bright light breaking through. As the Earth "
        "of Air, she is thought made concrete and defended: the altar is heavy and square, and in the "
        "corner, drawn precisely and clearly, the alchemical signs of Earth (🜃, a downward triangle "
        "crossed by a horizontal bar) and Air (🜁, an upward triangle crossed by a horizontal bar). Along "
        "the top, drawn precisely and clearly, the zodiac glyphs of Capricorn (♑, like a V joined to a "
        "looped tail), Aquarius (♒, two parallel zigzag lines) and Pisces (♓, two facing arcs joined by a"
        " horizontal line), marking her quadrant of the heavens. Palette: earth brown #8B6F47, olive, "
        "citrine, russet, slate storm-grey, black and pale gold #D9C23A; light breaks down through the "
        "clouds onto the blade and the altar. The whole image should feel like practical wisdom in "
        "action: firm, watchful, cutting away what is no longer needed."
    ),
}
