"""Scene per le immagini delle carte: Dischi. Una scena per carta, in inglese."""

SCENE = {
    "dischi-01": (
        "A single colossal disk of Earth fills the centre of the image, seen face-on and slightly tilted,"
        " nearly filling the frame: the primordial root of all matter, not heavy and still but spinning "
        "like a slow cosmic wheel. The disk is carved from pale gold-green stone, its surface ringed with"
        " concentric bands that suggest rotation, and from its rim spring six pairs of great feathered "
        "wings in cream and moss green, turning like the vanes of a turbine. At its heart, drawn "
        "precisely and clearly, a seven-rayed star encloses a smaller circle bearing the elemental "
        "triangle of Earth (a downward-pointing triangle crossed by a horizontal bar near its point), and"
        " around the inner rim runs a ring of tiny interlaced circles like orbiting seeds. Behind the "
        "disk, in the upper background, a point of blinding white light marks Kether (the first sphere of"
        " the Kabbalistic Tree, pure undivided being), and faint rays descend from it into the stone. In "
        "the lower foreground a dark fertile soil sprouts the first green shoots, and three faint "
        "zodiacal glyphs glow on the lower rim: Aries (♈, a ram's horns shaped like a Y), Taurus (♉, a "
        "circle with a crescent on top) and Gemini (♊, a Roman numeral two), drawn precisely. Palette: "
        "brilliant ivory white #F5F3E7, moss and leaf green #4A7C3A, citrine, soft gold, deep loam brown."
        " Light radiates from the white point above and from the disk itself. The whole image should feel"
        " like matter being born as living, whirling energy, the seed of every material blessing."
    ),
    "dischi-02": (
        "Two large disks hang one above the other on the vertical axis of the image, each slowly rotating"
        " in an opposite direction, and a long serpent coils around both of them in a figure-eight (a "
        "lemniscate, the sign of infinity), its tail in its mouth so that the loop never ends. The "
        "serpent is green-and-bronze scaled and wears a small crown of five points. The upper disk is "
        "pale grey with a yin-yang symbol (a circle divided into interlocking black and white teardrop "
        "halves, each with a dot of the opposite colour) whose white half is uppermost; the lower disk "
        "bears the same symbol reversed. Tiny elemental triangles orbit the disks: the upright triangle "
        "of Fire, the inverted triangle of Water, the barred upright triangle of Air and the barred "
        "inverted triangle of Earth. Near the upper disk glows the glyph of Jupiter (♃, a figure like a "
        "stylised 4 with a curved arm), near the lower disk the glyph of Capricorn (♑, a V-like stroke "
        "ending in a looped fish tail), both drawn precisely and clearly. The background is a soft "
        "pearl-grey mist evoking Chokmah (the second sphere of the Tree of Life, Wisdom, the dynamic "
        "Father), with a faint circular horizon suggesting the turning of the seasons. Palette: silvery "
        "grey #8A8D8F, dove grey, moss green #4A7C3A, bronze, black and white accents. Even diffused "
        "light, gently shifting. The whole image should feel like the perpetual, harmonious rhythm of "
        "change, one form flowing into the next without rupture."
    ),
    "dischi-03": (
        "Seen from directly above, a great four-sided pyramid of dressed stone rises at the centre, its "
        "apex pointing straight toward the viewer, its faces lit in graded tones so the geometric "
        "structure reads clearly. The pyramid rests on three massive disks set at the points of an "
        "upright triangle, like the wheels or foundation stones of a construction: the upper disk bears "
        "the alchemical sign of Mercury (☿, a circle with a small crescent on top and a cross below), the"
        " lower-left disk the sign of Sulphur (a triangle standing on a cross), the lower-right disk the "
        "sign of Salt (a circle divided by a horizontal line), all drawn precisely. The three disks are "
        "red-bronze, glowing like heated iron from the forge. Beneath everything spreads a dark, still, "
        "almost black sea, the Great Sea of Binah (the third sphere of the Tree of Life, the Great Mother"
        " who gives form, dark and Saturnine), with faint ripples of indigo. In the upper corners, drawn "
        "precisely and clearly, glow the glyph of Mars (♂, a circle with an arrow pointing up-right) and "
        "the glyph of Capricorn (♑, a V-like stroke ending in a looped fish tail). Thin crimson lines of "
        "force run from the disks up the edges of the pyramid like mortar being laid. Palette: deep black"
        " #1A1A1A, charcoal, indigo, moss green #4A7C3A, iron red, sandstone ochre. Light comes from the "
        "apex of the pyramid, as if the structure itself were becoming conscious. The whole image should "
        "feel like disciplined effort crystallising into solid, lasting construction."
    ),
    "dischi-04": (
        "A square fortress fills the centre of the image, seen in a slightly elevated frontal view with "
        "strict four-fold symmetry. Its walls are thick blocks of blue-grey stone; at each of the four "
        "corners stands a squat round tower crowned not by a roof but by a large embedded disk, so that "
        "the four disks mark the corners of a perfect square. Each disk bears one elemental triangle "
        "drawn precisely: upright triangle for Fire, inverted for Water, upright with a bar for Air, "
        "inverted with a bar for Earth. The central keep holds a closed gate of bronze, and a broad "
        "square moat of still water surrounds the whole fortress, reflecting it. Beyond the moat, in the "
        "background, lie ordered fields divided into rectangular plots under a deep royal blue sky, the "
        "colour of Chesed (the fourth sphere of the Tree of Life, Mercy and ordered law, the benevolent "
        "king). Above the keep, drawn precisely and clearly, shine the glyph of the Sun (☉, a circle with"
        " a dot at its centre) and the glyph of Capricorn (♑, a V-like stroke ending in a looped fish "
        "tail). A faint square grid of golden lines overlays the land, emphasising measurement and "
        "boundary. Palette: royal blue #1F4E9A, slate, moss green #4A7C3A, bronze, pale gold. Steady "
        "solar light falls from above and slightly left, casting firm shadows. The whole image should "
        "feel like established power and secure order, protective yet closed, on the edge of becoming a "
        "prison."
    ),
    "dischi-05": (
        "Five heavy disks are arranged in the shape of an inverted pentagram (a five-pointed star with a "
        "single point downward), linked by taut, crossing lines like strained cables or cracks in stone, "
        "so that the whole structure seems under stress and vibrating. The disks are dark iron with "
        "scarlet rims; each carries one of the five tattwa symbols (the Hindu elemental signs), drawn "
        "precisely: a yellow square for Earth, a silver crescent for Water, a red upward triangle for "
        "Fire, a blue circle for Air, and a black egg for Spirit. The lines between them are knotted, "
        "frayed and slightly bent, as though the geometry were grinding against itself. The background is"
        " a harsh scarlet and rust field, the colour of Geburah (the fifth sphere of the Tree of Life, "
        "Severity and strength), crossed by faint fissures like dry cracked earth. At the top of the "
        "image, drawn precisely and clearly, appear the glyph of Mercury (☿, a circle with a small "
        "crescent on top and a cross below) and the glyph of Taurus (♉, a circle with a crescent resting "
        "on it like horns). In the lower foreground a few fallen grains and a split clod of soil. "
        "Palette: scarlet #C8102E, rust, iron grey, dull moss green #4A7C3A, bruised brown. Light is cold"
        " and uneven, coming from the side and throwing jagged shadows. The whole image should feel like "
        "prolonged strain and material anxiety, a stability shaken that does not easily resolve."
    ),
    "dischi-06": (
        "At the centre of the image blazes a radiant golden sun, and on its face is set a rose-cross (an "
        "equal-armed cross with a red five-petalled rose blooming at the crossing), drawn precisely. "
        "Around it six disks form a perfect hexagram (a six-pointed star made of two interlaced "
        "triangles), each disk placed at one point of the star, and each bearing a planetary glyph drawn "
        "precisely and clearly: Saturn (♄, a cross with a hooked tail) at the top, Jupiter (♃, a stylised"
        " 4) and Mars (♂, a circle with an arrow up-right) on the upper sides, Venus (♀, a circle above a"
        " small cross) and Mercury (☿, a circle with crescent on top and a cross below) on the lower "
        "sides, and the Moon (☽, a crescent) at the bottom. The disks are polished gold with green enamel"
        " rims, and thin rays connect them to the central sun. Behind lies a warm field of concentric "
        "golden rings, evoking Tiphareth (the sixth sphere of the Tree of Life, Beauty and harmony, the "
        "solar heart of the Tree). Low in the image, drawn precisely, rest the glyph of the Moon (☽) and "
        "the glyph of Taurus (♉, a circle with a crescent resting on it like horns) among ripening wheat "
        "and blossoming green leaves. Palette: warm gold #E6B422, saffron, rose red, leaf green #4A7C3A, "
        "cream. Light radiates from the central sun outward. The whole image should feel like balanced, "
        "harmonious prosperity, bright yet as cyclical as the moon."
    ),
    "dischi-07": (
        "Seven heavy disks of dull grey lead lie across the image in the shape of the geomantic figure "
        "Rubeus (a vertical pattern of dots in four rows: two, one, two, two), drawn as a clear pattern "
        "so the arrangement reads at a glance. Each disk is tarnished and slightly sunk into the ground, "
        "and each is stamped with the glyph of Saturn (♄, a cross with a hooked tail) and the glyph of "
        "Taurus (♉, a circle with a crescent resting on it like horns), drawn precisely and clearly. "
        "Around and beneath the disks grows a field of vegetation that should be lush but is withered: "
        "wheat stalks bent and blackened, broad leaves curled and spotted, ears of grain rotting before "
        "they ripen. A few pale emerald shoots survive at the edges, hinting at Netzach (the seventh "
        "sphere of the Tree of Life, Victory, the green sphere of Venus and nature's fertility), now "
        "smothered. The background is a low, heavy sky of indigo and slate, clouds pressing down. In the "
        "foreground a cracked clay vessel lies empty on the soil. Palette: dull emerald #2E8B57, faded "
        "moss green #4A7C3A, lead grey, indigo, bruised olive, black. Light is weak and flat, filtered "
        "through thick cloud from above, with no clear source. The whole image should feel like effort "
        "that stalls under its own weight, a harvest spoiled by inertia and discouragement, yet not "
        "beyond future renewal."
    ),
    "dischi-08": (
        "A sturdy young tree with a thick trunk and carefully spreading branches rises from the centre of"
        " the lower image, rooted in dark tilled soil. Instead of fruit it bears eight round disks, like "
        "golden-orange fruits or closed flowers, hanging within broad protective leaves; they are "
        "arranged in the geomantic figure Populus (two vertical columns of four dots each, eight in all),"
        " a clear, orderly pattern. The disks are warm amber with fine concentric grain like the rings of"
        " a tree, and each is cradled by a leaf as if shaded from harsh light. The soil at the base is "
        "neatly worked into furrows and a small stone border marks the plot. The background is a soft "
        "orange sky, the colour of Hod (the eighth sphere of the Tree of Life, Splendour, the sphere of "
        "Mercury and practical intellect), fading to pale gold near the horizon. In the upper sky, drawn "
        "precisely and clearly, shine the glyph of the Sun (☉, a circle with a dot at its centre) and the"
        " glyph of Virgo (♍, a letter-M-like shape with a closed loop crossing its last stroke). Around "
        "the trunk stand a few wheat sheaves. Palette: burnt orange #E07B24, amber, leaf green #4A7C3A, "
        "earth brown, pale gold. Gentle late-afternoon sunlight from the upper left, warm and patient. "
        "The whole image should feel like slow, careful cultivation, skill and patience that will surely "
        "ripen into fruit."
    ),
    "dischi-09": (
        "Nine disks are arranged in a stable, symmetrical composition: three large disks stacked in a "
        "vertical column at the centre, touching one another like a pillar of coins, and six smaller "
        "disks arranged around them, three on each side, forming a protective hexagonal ring. The central"
        " three are silver, gold and copper; the six outer ones bear planetary glyphs drawn precisely: "
        "Saturn (♄, a cross with a hooked tail), Jupiter (♃, a stylised 4), Mars (♂, a circle with an "
        "arrow up-right), Sun (☉, a circle with a central dot), Venus (♀, a circle above a small cross) "
        "and Mercury (☿, a circle with a crescent on top and a cross below). Beneath the column lies a "
        "broad foundation stone, and under it a pool of violet shimmering light, evoking Yesod (the ninth"
        " sphere of the Tree of Life, the Foundation, the lunar violet sphere that gathers all forces "
        "before manifestation). Small green vines with blossoms climb between the disks. Above, drawn "
        "precisely and clearly, glow the glyph of Venus (♀) and the glyph of Virgo (♍, a letter-M-like "
        "shape with a closed loop crossing its last stroke). Palette: deep violet #6A3D9A, lavender, "
        "silver, gold, copper, leaf green #4A7C3A. Soft moonlike light from below mixes with warm light "
        "from the central column. The whole image should feel like good fortune gathered on firm ground, "
        "material gain that comes from luck wisely managed."
    ),
    "dischi-10": (
        "Ten disks are arranged in the pattern of the Kabbalistic Tree of Life (three vertical columns of"
        " circles linked by straight lines: one at the top, pairs descending on either side with single "
        "disks in the middle column, and one at the bottom), drawn as a clear diagram. Every disk is "
        "minted from gold and engraved with the glyph of Mercury (☿, a circle with a small crescent on "
        "top and a cross below), drawn precisely, and some also bear small caduceus wands and hexagrams. "
        "The lowest disk, at the base of the tree, is by far the largest, a massive coin set into the "
        "ground, representing Malkuth (the tenth sphere, the Kingdom, the material world), and it is "
        "quartered into citrine, olive, russet and black, the four colours of Malkuth. Around this great "
        "disk lie heaped coins, and thin golden streams flow from it back upward along the paths of the "
        "tree, so that wealth visibly circulates rather than stagnates. The background is a warm olive "
        "and ochre field with faint architectural arches suggesting a treasury. Near the top, drawn "
        "precisely and clearly, glow the glyph of Mercury (☿) and the glyph of Virgo (♍, a letter-M-like "
        "shape with a closed loop crossing its last stroke). Palette: antique gold #9C8A3E, citrine, "
        "olive, russet, black, moss green #4A7C3A. Rich, even light spreads from the great lower disk. "
        "The whole image should feel like the completion of material work, abundant wealth that must keep"
        " moving to stay alive."
    ),
    "dischi-cavaliere": (
        "A powerful knight in dark bronze-and-green armour rides a heavy draught horse across a ripe "
        "wheat field at harvest, moving in a slow, forceful diagonal from lower left to upper right. The "
        "horse is a massive, light-brown shire with feathered hooves pressing deep into the soil. The "
        "knight's visor is lowered; on his helmet rises a crest in the shape of a winged stag's head with"
        " broad antlers. Instead of a lance he holds a long flail raised over his shoulder, ready to "
        "thresh, and on his left arm hangs a round shield-disk bearing the elemental triangle of Earth (a"
        " downward-pointing triangle with a horizontal bar near its point) with a small upright triangle "
        "of Fire (a plain upward triangle) inset above it, showing him as fire of earth, drawn precisely."
        " Behind him, in the background, rise sunlit hills and distant blue mountains, and the sky glows "
        "hot orange at the horizon, with a faint grey sphere above evoking Chokmah (the second sphere of "
        "the Tree of Life, the dynamic Father). In the sky, drawn precisely and clearly, shine the glyph "
        "of Leo (♌, a looped stroke like a lion's mane and tail) and the glyph of Virgo (♍, a "
        "letter-M-like shape with a closed loop crossing its last stroke), marking his span from late Leo"
        " to Virgo. Palette: burnt orange #FF7F24, golden wheat, moss green #4A7C3A, bronze, earthen "
        "brown. Strong late-summer sunlight from the right. The whole image should feel like steady, "
        "laborious strength bringing in the harvest."
    ),
    "dischi-regina": (
        "A mature queen sits enthroned at the centre on a throne carved from grey rock, facing the viewer"
        " with calm receptivity. She wears a flowing robe of deep green over blue-grey, and on her head "
        "is a helmet-crown topped by a crest shaped as a winged goat's head with curved horns. In one "
        "hand she holds a sceptre ending in a cube, and in the other a globe formed of interlaced golden "
        "circles, like an armillary sphere. The landscape behind her is divided: on her left spreads an "
        "arid, cracked desert of sand and stone; on her right a winding river flows down and waters a "
        "strip of land where green grass, palms and flowers are blooming. Beside the throne, standing on "
        "a rock, is a sturdy mountain goat with twisted horns. At her feet, drawn precisely, is the "
        "elemental triangle of Earth (a downward-pointing triangle with a horizontal bar near its point) "
        "with a small inverted triangle of Water (a plain downward triangle) inside it, showing water of "
        "earth. In the sky, drawn precisely and clearly, shine the glyph of Sagittarius (♐, an arrow "
        "pointing up-right with a short crossbar) and the glyph of Capricorn (♑, a V-like stroke ending "
        "in a looped fish tail). A dark sphere hovers faintly above, evoking Binah (the third sphere of "
        "the Tree of Life, the Great Mother). Palette: steel blue #4682B4, moss green #4A7C3A, sand "
        "ochre, slate grey, soft black. Gentle light falls from the river side. The whole image should "
        "feel like patient, fertile care, barren land made to bloom."
    ),
    "dischi-principe": (
        "A young prince sits upright in a heavy, square wooden chariot drawn by a powerful ox, advancing "
        "slowly toward the viewer along a road that cuts through cultivated fields, with a clear sense of"
        " forward direction. The ox is broad and calm, with polished horns and a flower garland on its "
        "neck. The prince wears light armour of green and straw-yellow, and on his helmet rises a crest "
        "in the shape of a winged bull's head. In his right hand he holds a sceptre topped by a "
        "cross-and-orb, in his left a globe marked with the elemental triangle of Earth (a "
        "downward-pointing triangle with a horizontal bar near its point) combined with the triangle of "
        "Air (an upward triangle crossed by a horizontal bar), showing air of earth, drawn precisely. The"
        " chariot's wheels are large disks engraved with furrow patterns. Behind him extends an orderly "
        "landscape: ploughed fields, irrigation canals, flowering orchards and a road leading to a "
        "distant town, all laid out with intelligent planning. A golden sphere glows in the upper "
        "background, evoking Tiphareth (the sixth sphere of the Tree of Life, Beauty, the harmonious "
        "solar centre). In the sky, drawn precisely and clearly, shine the glyph of Aries (♈, a ram's "
        "horns shaped like a Y) and the glyph of Taurus (♉, a circle with a crescent resting on it like "
        "horns). Palette: pale khaki yellow #F0E68C, moss green #4A7C3A, straw, warm brown, sky blue. "
        "Clear spring morning light from the left. The whole image should feel like patient intelligence "
        "turning the land into fertile, well-ordered work."
    ),
    "dischi-principessa": (
        "A young, strong princess stands at the centre, rooted firmly on the ground, gravely beautiful "
        "and visibly expectant with child under a loose robe of russet and olive, her pose calm and "
        "inward. On her head rests a crown with curled ram's horns as its crest. With her right hand she "
        "plants a long sceptre straight down into the earth, where its tip becomes a root; with her left "
        "she holds a large disk before her womb, carved as a stylised rose of many petals, with a faint "
        "seed of light at its centre. Around her stands a sacred grove of dark trees, and at her feet "
        "rests a small stone altar heaped with wheat sheaves; the ground is rich black soil scattered "
        "with crystals. Beneath her, drawn precisely, lies the elemental triangle of Earth (a "
        "downward-pointing triangle with a horizontal bar near its point) doubled, one inside the other, "
        "showing earth of earth. In the upper sky, drawn precisely and clearly, glow the glyphs of Aries "
        "(♈, a ram's horns shaped like a Y), Taurus (♉, a circle with a crescent resting on it like "
        "horns) and Gemini (♊, a Roman numeral two), the celestial quadrant she rules. The ground is "
        "quartered in the four colours of Malkuth (the tenth sphere of the Tree of Life, the Kingdom): "
        "citrine, olive, russet and black. Palette: warm brown #8B6F47, moss green #4A7C3A, olive, "
        "citrine, black. Soft light rises from the rose-disk itself. The whole image should feel like "
        "earth pregnant with hidden light, about to be reborn."
    ),
}
