"""Scene per le immagini delle carte: Arcani maggiori. Una scena per carta, in inglese."""

SCENE = {
    "maj-00": (
        "A vast luminous spiral vortex fills the whole image, turning clockwise out of a pale "
        "golden-white void; at its centre, slightly above middle, strides a young horned god of spring, "
        "green-skinned and laughing, with small curved horns sprouting from his curly hair, a "
        "crescent-shaped glow between them, dressed in a loose tunic of new leaves and carrying in one "
        "raised hand a flaming pine-cone wand and in the other a glowing crystal cup. He steps forward "
        "off nothing, feet above empty air, carefree. Wound into the arms of the spiral around him are "
        "his companions: a striped tiger playfully leaping at his calf in the lower left, a green "
        "crocodile rising from swirling water at the bottom right, a white dove descending from the top, "
        "a butterfly, and heavy bunches of purple grapes and ivy spilling along the curve. Behind his "
        "head, drawn precisely and clearly in shining gold, the Hebrew letter Aleph (א, a glyph shaped "
        "like a slanted diagonal bar with an upper and a lower hook, like an ox-yoke), and in the air to "
        "the right the alchemical triangle of Air (an upward triangle crossed by a horizontal line). At "
        "the very top two faint radiant spheres, white and grey, joined by a thin line of light (path 11 "
        "linking Kether, the Crown, and Chokmah, Wisdom). Palette: pale lemon #FFF8A6, sky blue #87CEEB, "
        "fresh spring green #7FC75A, white-gold highlights; light pours from behind the figure out of the"
        " void itself. The whole image should feel like pure potential before creation, innocent, "
        "divinely mad, weightless and joyful."
    ),
    "maj-01": (
        "A tall youthful winged figure, Mercury as the divine magician, hovers in the exact centre in a "
        "dynamic cross-shaped pose, one arm raised high and one lowered toward the earth, a slender "
        "caduceus staff (a winged rod entwined by two serpents) running vertically through his body like "
        "an axis of light. He wears an iridescent violet tunic and a winged cap. Around him, floating in "
        "a circular orbit as if he is juggling them in midair, spin the instruments of his art: a wand, a"
        " cup, a sword, a golden disk, a scroll, a stylus, a winged egg and a small flame. Below him to "
        "the left squats a grey cynocephalus ape (a dog-headed baboon, sacred to Thoth) mimicking his "
        "gesture with a mocking grin, a reminder that every word can be distorted. Painted precisely and "
        "clearly on his chest is the astrological glyph of Mercury (☿, a circle on a cross with a small "
        "crescent like horns on top), and above his head in radiant gold the Hebrew letter Beth (ב, a "
        "glyph shaped like a square open house or bracket with a flat base extending right). At the top a"
        " white sphere joined by a vertical shimmering line to a dark indigo sphere (path 12 linking "
        "Kether, the Crown, and Binah, Understanding). Palette: bright yellow #FFE135, deep violet "
        "#7B3F9E, silver-grey, gold sparks; light radiates from the figure itself against a dark indigo "
        "field. The whole image should feel like pure will and intelligence in motion, quicksilver, "
        "electric, creative."
    ),
    "maj-02": (
        "A serene goddess, Isis and the virgin huntress Artemis in one, sits enthroned at the centre in "
        "strict frontal symmetry, veiled from head to feet in a net of fine luminous silver threads that "
        "both reveals and hides her form. Across her knees rests a silver hunting bow, her hands laid "
        "lightly upon it. A thin silver crescent rests on her brow. Behind her rise two pillars, one "
        "black and one white, merged into a curtain of shimmering light rather than stone. At her feet in"
        " the foreground a still pool reflects everything, and from it grow a few crystals, seed pods, "
        "fruits and flowers; a small camel stands in the distance at the lower right edge of the water. "
        "Painted precisely and clearly above her head, the astrological glyph of the Moon (☽, a thin "
        "crescent open to the left) and in silver on her breast the Hebrew letter Gimel (ג, a glyph like "
        "a tall vertical stroke with a small foot kicking out to the left at the base, evoking a camel's "
        "neck and stride). A long vertical ray of pale light descends from a white sphere at the top to a"
        " golden sphere at the bottom behind her (path 13 linking Kether, the Crown, to Tiphareth, "
        "Beauty, crossing the desert of the Abyss). Palette: cobalt blue #0047AB, silver #C0C0C0, pearl "
        "white, deep night blue; soft cold moonlight from above. The whole image should feel like "
        "untouched spiritual purity, a secret intuition, stillness before any revelation."
    ),
    "maj-03": (
        "A majestic crowned woman, the Empress as mother and bride, sits on a throne whose back rises in "
        "curved blue flames, in a gentle three-quarter pose, her arms and body forming the shape of the "
        "alchemical symbol of Salt (a circle bisected by a horizontal line) around her torso. In emerald "
        "and sky-blue robes embroidered with bees, she holds a lotus sceptre in her right hand. The "
        "composition is a soft arch shape: in the foreground at her feet a white pelican stands on its "
        "nest, piercing its breast to feed three chicks with its blood; to her left a heraldic shield "
        "displays a white two-headed eagle bearing a red moon; behind her is a doorway framed by an arch "
        "of roses, and beyond it a green blossoming garden and a crescent moon. Painted precisely and "
        "clearly on the back of the throne is the astrological glyph of Venus (♀, a circle above a small "
        "cross), and above the door the Hebrew letter Daleth (ד, a glyph shaped like a door or an "
        "upside-down L, a horizontal roof with a vertical stroke on the right). A horizontal band of "
        "light runs across the top of the image between a grey sphere and a dark sphere (path 14 linking "
        "Chokmah, Wisdom, and Binah, Understanding). Palette: emerald green #50C878, sky blue #87CEEB, "
        "rose pink, gold; warm diffuse morning light from the left. The whole image should feel like "
        "fertile love, abundance and the welcoming form that receives force, lush and tender."
    ),
    "maj-04": (
        "A powerful bearded emperor sits in profile-to-three-quarter view at the centre on a massive "
        "stone throne, his body forming a triangle set above a cross (the alchemical symbol of Sulphur, "
        "an upward triangle standing on a cross), arms and head making the triangle, crossed legs making "
        "the cross. He wears scarlet armour and a flame-red cloak, a crown with fleur-de-lis points, "
        "holds a sceptre topped with a ram's head in his right hand and an orb bearing a cross in his "
        "left. At each side of the throne, rising behind his shoulders, are the heads of two great wild "
        "Himalayan rams with spiralling horns; at his feet lies a lamb holding a small pennant, and on "
        "his shield a heraldic eagle with a red disk. A single golden bee and a golden fleur-de-lis are "
        "set symmetrically on the base of the throne as heraldic emblems. Painted precisely and clearly "
        "above his head, the astrological glyph of Aries (♈, a ram's horns shaped like a V with curled "
        "tops) and on the throne the Hebrew letter Tzaddi (צ, a glyph like a hook with a small upright "
        "arm on its right, resembling a fish-hook). A diagonal red beam runs between a grey sphere at "
        "upper right and a golden sphere lower left (path 15 linking Chokmah, Wisdom, and Tiphareth, "
        "Beauty). Palette: scarlet #FF2400, firebrick #B22222, gold, black shadows; hot sunrise light "
        "from the right. The whole image should feel like creative energy made into order, authority, "
        "initiative and paternal power."
    ),
    "maj-05": (
        "A tall robed priest-king, the Hierophant, sits enthroned at the centre on a great white bull "
        "whose horned head fills the lower foreground, flanked by two elephants in the shadows at left "
        "and right; the four Kerubim (a man, an eagle, a lion and a bull, as carved masks) watch from the"
        " four corners. He wears layered robes of deep orange and dark violet, a tall mitre, and holds a "
        "sceptre topped with three interlaced rings. He smiles faintly, secretively. On his breast glows "
        "a five-pointed star (a pentagram) and inside it dances a small naked child, the new god Horus, "
        "stylised as a silhouette of golden light; around him is a larger six-pointed hexagram. Before "
        "him in the foreground stands a young woman in armour holding a sword and a crescent moon, "
        "representing the Scarlet Woman of the new age. Behind his head is a round stained-glass window "
        "with nine nails around it. Painted precisely and clearly on the window, the astrological glyph "
        "of Taurus (♉, a circle with an upturned crescent like horns on top) and, above, the Hebrew "
        "letter Vau (ו, a glyph like a simple vertical nail with a small hooked head). A thin line of "
        "light links a grey sphere above to a blue sphere at his right (path 16 linking Chokmah, Wisdom, "
        "and Chesed, Mercy). Palette: burnt orange #E2582C, deep aubergine #2E1A47, indigo, muted gold; "
        "dim temple light filtered through the window. The whole image should feel like sacred teaching "
        "and tradition that secretly carries a new revelation."
    ),
    "maj-06": (
        "A solemn alchemical wedding in a tall arched chamber: in the centre stands a hooded, cloaked "
        "hermit-like figure whose arms are extended in blessing, joining the hands of a black crowned "
        "king on the left and a white crowned queen on the right, exactly mirrored. The king holds a "
        "spear beside a red lion; the queen holds a cup beside a white eagle. In the foreground two small"
        " children, one dark and one pale, hold a club and a bunch of roses; between them lies a winged "
        "orphic egg wrapped by a serpent. Above the hooded figure, in an arch of light, a blindfolded "
        "winged Cupid draws his bow, the arrow aimed down at the couple. Along the upper arch are the "
        "figures of Eve and Lilith faintly carved. Painted precisely and clearly on the keystone, the "
        "astrological glyph of Gemini (♊, a Roman numeral II shape with curved top and bottom bars) and "
        "on the hood of the central figure the Hebrew letter Zain (ז, a glyph like a vertical sword "
        "stroke topped with a small horizontal head, shaped like a sword or hilt). A diagonal line of "
        "light runs from a dark sphere at upper left to a golden sphere at lower centre (path 17 linking "
        "Binah, Understanding, and Tiphareth, Beauty). Palette: bright orange #FF8C00, thistle lilac "
        "#D8BFD8, black and white contrasts, gold; soft light from above through the arch. The whole "
        "image should feel like the union of opposites, choice, attraction and the first stage of a great"
        " transformation."
    ),
    "maj-07": (
        "A heavy ceremonial chariot seen head-on fills the centre, with a canopy of deep blue sky and "
        "stars supported by four pillars. Inside sits a charioteer entirely encased in golden amber "
        "armour, completely still, with no reins in his hands; instead he holds before his chest a "
        "spinning disk, the Holy Grail, a round cup of clear amethyst with blood-red light in its centre,"
        " radiating rays. His helmet is crowned with a crab, and ten stars decorate his armour. The "
        "chariot is pulled by four sphinxes in the foreground, each a composite creature of bull, lion, "
        "eagle and man combined in different ways, representing the four elements, crouched and moving in"
        " unison although no one steers them. The wheels are wide and scarlet, turning in a river-like "
        "mist of motion. Painted precisely and clearly on the front of the chariot, the astrological "
        "glyph of Cancer (♋, two small circles each with a curved tail, set in a sideways 69 shape) and "
        "on the canopy the Hebrew letter Cheth (ח, a glyph shaped like a gateway or fence: two vertical "
        "strokes joined by a roof across the top). A line of light descends from a dark sphere at upper "
        "left to a red sphere below (path 18 linking Binah, Understanding, and Geburah, Severity). "
        "Palette: amber #FFBF00, maroon #800000, midnight blue, silver; bright light from the Grail "
        "itself. The whole image should feel like victory through stillness, self-mastery and a will so "
        "centred that it moves the world without effort."
    ),
    "maj-08": (
        "A slender woman, Maat the goddess of balance, stands at the exact centre poised on the tips of "
        "her toes, perfectly vertical, as if dancing on a single point; the composition is a strict "
        "vertical axis crossed by a horizontal beam, like a diamond inside a larger lozenge. Her face is "
        "hidden behind a smooth, pale, serene mask, and she wears a flowing green gown and a "
        "harlequin-like cloak of green and blue triangles. With both hands she grips the hilt of a long "
        "sword pointing straight down between her feet. From her tall ostrich-feather headdress hangs a "
        "pair of golden scales: in one pan the Greek letter Alpha (Α), in the other the letter Omega (Ω),"
        " exactly balanced. On either side of her, spheres of light and darkness hover in counterpoise, "
        "and behind her a curtain of fine lines forms a diamond. Painted precisely and clearly at her "
        "feet, the astrological glyph of Libra (♎, a horizontal line with a raised hump or arch above it,"
        " like a setting sun over the horizon) and on the sword's hilt the Hebrew letter Lamed (ל, a "
        "glyph shaped like an ox-goad: a tall upright stroke curving down into a hook). A line of light "
        "links a red sphere at upper left to a golden sphere below (path 22 linking Geburah, Severity, "
        "and Tiphareth, Beauty). Palette: emerald green #50C878, dodger blue #1E90FF, pale gold, soft "
        "white; even, cool light from every side with no shadows. The whole image should feel like exact "
        "equilibrium, justice as the natural correction of every excess."
    ),
    "maj-09": (
        "A tall old hermit in a heavy, dark-red hooded cloak stands bent in the right half of the image, "
        "his back curved like the Hebrew letter Yod, his face in shadow, gazing into a lantern he holds "
        "forward in his right hand. Inside the lantern burns a small blazing sun, radiating golden rays "
        "that illuminate the scene. He stands in the midst of a golden wheat field that fills the "
        "foreground. At his feet sits the three-headed dog Cerberus, tamed and quiet, following him. In "
        "the lower left, a large glowing orphic egg wrapped in a coiled serpent sits among the wheat. "
        "Behind him, floating in the air as a delicate abstract motif, a luminous spiralling form like a "
        "sperm cell swims upward, symbol of the secret seed of life. Painted precisely and clearly on the"
        " lantern's glass, the astrological glyph of Virgo (♍, an M-shape whose final stroke curls inward"
        " with a small loop) and above his head, glowing, the Hebrew letter Yod (י, a glyph like a small "
        "flame or comma hanging from the top line, the smallest letter). A thin line of light runs from a"
        " blue sphere at upper left to a golden sphere (path 20 linking Chesed, Mercy, and Tiphareth, "
        "Beauty). Palette: yellow-green #9ACD32, slate grey #708090, wheat gold, dark cloak red; the only"
        " light is from the lantern sun in a dusky atmosphere. The whole image should feel like silent "
        "inner search, wisdom preserved in secret, and the hidden light of life passing on."
    ),
    "maj-10": (
        "A great ten-spoked wheel dominates the whole image, set slightly tilted in a turbulent violet "
        "sky full of lightning bolts and stars. On top of the wheel sits a sphinx armed with a sword, "
        "composed of lion, bull, eagle and man; on the rising right side climbs Hermanubis, a "
        "jackal-headed figure with a monkey's body holding a caduceus; on the descending left side falls "
        "Typhon, a crocodile-headed dark serpent-bodied creature plunging downward. These three figures "
        "embody the three gunas of Hindu philosophy (tamas inertia, rajas activity, sattva calm) and the "
        "three alchemical principles, Salt, Sulphur and Mercury. The wheel's hub is a radiant ten-pointed"
        " star, and each of the ten spokes ends in a small shining sphere. Streaks of blue lightning and "
        "white stars alternate in the background, showing the eternal cycle of change. Painted precisely "
        "and clearly at the hub, the astrological glyph of Jupiter (♃, a figure like the numeral 4 with a"
        " curved left arm) and on the rim, in gold, the Hebrew letter Kaph (כ, a glyph shaped like a "
        "cupped hand or a backward C with flat top and bottom). A diagonal line of light links a blue "
        "sphere at upper right to a green sphere at lower right (path 21 linking Chesed, Mercy, and "
        "Netzach, Victory). Palette: electric violet #8F00FF, medium blue #0000CD, royal purple, silver "
        "and gold highlights; flashing, shifting light from the lightning. The whole image should feel "
        "like the inevitable motion of fortune, sudden change, and the wheel of destiny that turns "
        "everything."
    ),
    "maj-11": (
        "A radiant woman, the Scarlet Woman Babalon, rides astride a gigantic lion-like beast with seven "
        "heads, its body rolling in a powerful diagonal from lower left to upper right; she leans back "
        "ecstatically, hair flowing, draped in a flowing red and violet robe, holding the reins of the "
        "beast in her left hand and raising high above her head a glowing golden grail cup blazing with "
        "flame in her right hand. The seven heads of the beast each differ: an angel, a saint, a poet, a "
        "bacchante, a warrior, a satyr and a lion-serpent, all crowned. Beneath the beast's paws lie "
        "faint pale ghostly figures of saints and old values, overcome. In the background ten luminous "
        "circles radiate like a halo, and serpentine rays of light fan outward. Painted precisely and "
        "clearly above the grail, the astrological glyph of Leo (♌, a loop with a long curving tail like "
        "a lion's mane), and on the beast's flank the Hebrew letter Teth (ט, a glyph shaped like a coiled"
        " serpent: a rounded vessel with its right side curling inward at the top). A horizontal band of "
        "light runs between a blue sphere at right and a red sphere at left (path 19 linking Chesed, "
        "Mercy, and Geburah, Severity). Palette: chartreuse yellow #DFFF00, indigo #4B0082, scarlet, "
        "bright gold; hot sunlit glow from the grail and the flames. The whole image should feel like "
        "joyful vitality, passion and courage that tames the beast by embracing it, ecstatic and "
        "fearless."
    ),
    "maj-12": (
        "A young man hangs upside down at the centre, his body forming an inverted triangle with a cross "
        "above it: his crossed legs form the cross, his arms stretched outwards to form the triangle. He "
        "is suspended by one foot from a large golden ankh (the Egyptian cross of life, a T shape with a "
        "loop on top), attached by a silver cord. His body is bound to a geometric grid of green squares,"
        " like tablets of an elemental magic square, forming the background pattern; nails pierce his "
        "palms and feet in a stylised non-violent way, rendered as small points of light. His face is "
        "calm, eyes closed, serene. At the bottom, below his head, a coiled green serpent rises from dark"
        " water, heralding new life. Around him are dark blue waves forming a circle. Painted precisely "
        "and clearly on the ankh, the alchemical triangle of Water (a downward-pointing triangle) and in "
        "silver below the serpent the Hebrew letter Mem (מ, a glyph shaped like waves: a wavy top stroke "
        "with a vertical right side and a gap at the bottom left). A thin line of light runs down between"
        " a red sphere above and an orange sphere below (path 23 linking Geburah, Severity, and Hod, "
        "Splendour). Palette: deep blue #00338D, sea green #2E8B57, pale gold, cold white; soft greenish "
        "underwater light filtering from above. The whole image should feel like sacrifice and surrender,"
        " the stillness of suspension that awaits rebirth."
    ),
    "maj-13": (
        "A tall black skeleton crowned with the crown of Osiris (a tall white crown flanked by feathers) "
        "dances wildly in the centre, swinging a long curved scythe in a sweeping arc. As the blade cuts "
        "through the air it releases countless iridescent bubbles, and inside each bubble a tiny new form"
        " is already sprouting: a seed, a fish, a flower, a tiny human figure. At the skeleton's feet in "
        "the foreground, a scorpion crawls out of the dark water; a serpent coils along the bottom edge; "
        "and a fish swims up into the air. Behind, rising from a burnt landscape, a white eagle soars "
        "upward on the left. The dance forms a diagonal spiral movement from bottom right to top left, "
        "and the arc of the scythe echoes a crescent. Painted precisely and clearly at the top of the "
        "scythe's handle, the astrological glyph of Scorpio (♏, an M-shape whose last stroke ends in an "
        "upward-pointing arrow like a stinger) and on the skeleton's chest the Hebrew letter Nun (נ, a "
        "glyph like a curved vertical hook with a short base, resembling a fish). A line of light joins a"
        " golden sphere at upper left with a green sphere at right (path 24 linking Tiphareth, Beauty, "
        "and Netzach, Victory). Palette: dark cyan #008B8B, coffee brown #6F4E37, bone white, deep "
        "indigo; dim cold glow reflected off the bubbles. The whole image should feel like death as "
        "transformation, a step in the endless dance of life, not its end."
    ),
    "maj-14": (
        "An androgynous alchemist with two faces, one pale and one dark, stands at the centre wearing a "
        "green robe embroidered with bees and serpents; the figure is the fusion of a king and a queen, "
        "one arm white and one arm black. With one hand the figure pours a stream of fire from a torch "
        "and with the other a stream of water from a vessel, both crossing and mixing in a large golden "
        "cauldron at the bottom, from which rises a rainbow-like arc. On the left a white lion breathes "
        "flames into the cauldron, on the right a red eagle drips water into it: the elements are "
        "exchanged. Behind the head glows an egg-shaped arch. Across the upper background, like an "
        "inscription on a golden band, are the letters V.I.T.R.I.O.L. (initials of the Latin alchemical "
        "motto visit the interior of the earth and by rectifying you will find the hidden stone). Painted"
        " precisely and clearly on the cauldron, the astrological glyph of Sagittarius (♐, an arrow "
        "pointing up-right with a short crossbar), and on the figure's brow the Hebrew letter Samekh (ס, "
        "a glyph like a closed circle with a small flat top). A vertical line of light links a golden "
        "sphere above to a violet sphere below (path 25 linking Tiphareth, Beauty, and Yesod, "
        "Foundation). Palette: electric blue #1F51FF, gold #FFD700, fiery red, emerald; warm light from "
        "the cauldron. The whole image should feel like the art of alchemical synthesis, balance, patient"
        " mixing of opposites into something new."
    ),
    "maj-15": (
        "A great Himalayan goat, Pan the generator, stands frontally at the centre with enormous "
        "spiralling horns, a wise laughing face and a third eye glowing between the horns; he stands on a"
        " mountain peak at the summit of the world, above distant snowy ridges. Between his horns is a "
        "glowing winged disk; behind him rises a tall column-like staff capped with a winged sun, "
        "entwined by two serpents. Below the peak, on either side, are two transparent globes forming a "
        "symmetrical vessel, each containing tiny human figures struggling upward and trying to escape, "
        "bound only by their own desire. At the bottom, grapes and vines crawl over the rocks. The "
        "composition is a strong vertical axis, the goat's horns forming a rough spiral crown across the "
        "top. Painted precisely and clearly on the staff, the astrological glyph of Capricorn (♑, a "
        "V-shape whose right stroke loops into a curl like a goat-fish tail), and between the goat's "
        "horns the Hebrew letter Ayin (ע, a glyph like a Y whose right arm curves down to the base, "
        "suggesting an eye). A diagonal line of light runs from a golden sphere above to an orange sphere"
        " below (path 26 linking Tiphareth, Beauty, and Hod, Splendour). Palette: deep indigo-violet "
        "#3B1F6B, near-black #1C1C1C, pale grey rock, amber glints; cold grey light with glowing violet "
        "shadows. The whole image should feel like raw creative instinct, desire and material ambition, "
        "fertile, humorous and without moral judgement."
    ),
    "maj-16": (
        "A massive stone tower stands at the centre, broken and crumbling, its top shattered and flying "
        "apart. Above it, filling the upper third, is a great blazing eye of Horus (a stylised Egyptian "
        "eye with a teardrop line beneath it), shooting a bolt of lightning straight down into the tower."
        " From the bottom right, the gaping jaws of Dis, a huge fiery hellmouth, belch flames that engulf"
        " the base of the building. Stylised geometric human figures fall from the tower through the air."
        " In the upper left a white dove carrying an olive branch flies away peacefully, and in the upper"
        " right a lion-headed serpent coils upward, symbol of renewed desire. The composition is "
        "explosive, with shards and fragments radiating outward from the centre. Painted precisely and "
        "clearly in the flames at the bottom, the astrological glyph of Mars (♂, a circle with an arrow "
        "pointing up-right) and on a falling stone block the Hebrew letter Pe (פ, a glyph like a mouth: a"
        " curved open square with a small inner hook at the top). A horizontal line of light runs across "
        "between a green sphere at right and an orange sphere at left (path 27 linking Netzach, Victory, "
        "and Hod, Splendour). Palette: bright red #FF0000, crimson #C1121F, black smoke, blazing yellow; "
        "violent light from the lightning and flames. The whole image should feel like sudden destruction"
        " of false structures, liberation that brings peace, an awakening."
    ),
    "maj-17": (
        "A tall graceful female figure, Nuit the goddess of the starry sky, kneels on one knee at the "
        "edge of a calm sea in the lower centre, her body forming a gentle curve. She holds two cups: "
        "from a golden cup raised high in her right hand she pours shining water over her own head, and "
        "from a silver cup lowered in her left hand she pours water into the sea; the two streams form a "
        "spiral that flows into the pool and the earth. Behind her hangs a large seven-pointed star (the "
        "star of Babalon, a heptagram) shining with silver light, and around it smaller stars spiral in a"
        " galaxy-like vortex. On the right, among crystal rocks, bloom roses and small lilies; in the "
        "background is a globe partly covered with stars. Her long flowing hair falls blue-violet like "
        "the night sky. Painted precisely and clearly on the golden cup, the astrological glyph of "
        "Aquarius (♒, two parallel zigzag wavy lines), and in the star's centre, glowing, the Hebrew "
        "letter He (ה, a glyph shaped like an open window: a horizontal roof with a vertical stroke on "
        "the right and a short separate stroke hanging on the left). A line of light descends from a "
        "green sphere at upper left to a violet sphere below (path 28 linking Netzach, Victory, and "
        "Yesod, Foundation). Palette: violet #8F00FF, sky blue #87CEEB, silver, soft gold; gentle "
        "starlight from the heptagram. The whole image should feel like hope, renewal and the calm, "
        "infinite inspiration of the stars."
    ),
    "maj-18": (
        "A narrow path runs from the foreground into the distance between two tall black towers at left "
        "and right, forming a symmetrical gateway under a waning crescent moon that hangs low and "
        "dripping with drops of blood-like dew. In front of each tower stands a jackal-headed Anubis "
        "figure, one dark and one pale, holding a staff, and at their feet a jackal crouches, guardians "
        "of the threshold. The path winds through a desolate, eerie landscape of hills; in the foreground"
        " a stream of dark water fills the lower third, and at its centre a great scarab beetle rises "
        "from the water, carrying a golden solar disk between its forelegs, pushing the sun toward the "
        "morning. The water shows faint wavy lines like sound vibrations. Painted precisely and clearly "
        "above the gate, the astrological glyph of Pisces (♓, two crescents facing away from each other "
        "joined by a horizontal line), and on the scarab's back the Hebrew letter Qoph (ק, a glyph like "
        "the back of a head: a rounded hook on top with a long descending tail below the line). A long "
        "vertical line of light runs from a green sphere at the top right to an earthy sphere at the "
        "bottom (path 29 linking Netzach, Victory, and Malkuth, the Kingdom). Palette: dark raspberry "
        "#8B0A50, pale gold #E0C589, black, murky violet; cold moonlight from above with glints on the "
        "water. The whole image should feel like a disturbing threshold, illusion and dream, the dark "
        "passage before dawn."
    ),
    "maj-19": (
        "A great radiant sun fills the upper half, a golden disk with twelve rays; around it in a large "
        "circle are the twelve zodiac signs drawn clearly as small glyphs, forming a wheel of the "
        "heavens. Below, on a green hill encircled by a low red brick wall, two winged children dance "
        "joyfully, facing each other, arms raised, one with a dark skin and one with a fair skin, their "
        "small wings shining; around them grow roses and sunflowers. The composition is centred, with the"
        " sun directly above the children, and the wall arcs around the hill as a limit that humanity is "
        "invited to go beyond. A rose-cross (a cross with a rose at its centre) is inscribed on the hill "
        "in the grass. Painted precisely and clearly in the centre of the sun, the astrological glyph of "
        "the Sun (☉, a circle with a dot in its centre), and in the rays above, the Hebrew letter Resh "
        "(ר, a glyph like a head in profile: a rounded right angle with a smooth curve at the top right "
        "corner). A line of light links an orange sphere at left and a violet sphere below (path 30 "
        "linking Hod, Splendour, and Yesod, Foundation). Palette: bright orange #FFA500, gold #FFD700, "
        "grass green, warm red; bright midday sunlight pouring from above. The whole image should feel "
        "like joy, vitality, clarity and the freedom of a new age, radiant and uncomplicated."
    ),
    "maj-20": (
        "The image is structured like an Egyptian stele: across the top arches the dark blue body of the "
        "goddess Nuit, curved over the whole scene, her body covered with stars, forming the frame of the"
        " sky. Beneath her in the upper centre floats a winged globe, the golden sun disk of Hadit with "
        "outstretched falcon wings. In the middle, in a sphere of light like a womb, sits the child god "
        "Horus, Harpocrates, in a transparent fetal form with his finger at his lips, while behind him, "
        "larger and fainter, the enthroned figure of Ra-Hoor-Khuit, the falcon-headed god, sits with his "
        "wand. At the bottom, human figures rise from the earth like seedlings, their arms raised to the "
        "light. Great tongues of fire rise in three columns from the base. Painted precisely and clearly "
        "at the bottom centre, the alchemical triangle of Fire (an upward-pointing triangle) and above, "
        "burning, the Hebrew letter Shin (ש, a glyph like three flames or three upward prongs joined at a"
        " common base, like a trident). A line of light runs from an orange sphere at upper left to an "
        "earthy sphere at the bottom (path 31 linking Hod, Splendour, and Malkuth, the Kingdom). Palette:"
        " orange-red #FF4500, vermilion #E34234, deep blue, gold; an intense glow rising from the fire, "
        "as if dawn were breaking from below. The whole image should feel like final judgement become "
        "awakening, the birth of a new age of the spirit."
    ),
    "maj-21": (
        "A slender dancing woman, lightly veiled, whirls at the centre inside a large vertical ellipse of"
        " seventy-two luminous segments (the seventy-two names of God, arranged as a ring of small arcs)."
        " She dances with a great coiling serpent, holding its body in her raised hands, and the "
        "serpent's coils form a spiral of energy rotating around her. Below her feet is a geometric "
        "diagram, a pattern of intersecting lines and circles, the scheme of the elements and the "
        "structure of matter, like a crystalline grid. At the four corners of the image are the four "
        "Kerubim, the fixed signs of the zodiac, painted as heads spouting streams of water: a man "
        "(Aquarius), an eagle (Scorpio), a lion (Leo) and a bull (Taurus). Painted precisely and clearly "
        "at the top of the ellipse, the astrological glyph of Saturn (♄, a small cross whose lower stroke"
        " curves out into a hook like the letter h), and at the bottom the Hebrew letter Tau (ת, a glyph "
        "shaped like a gateway with a small foot at the bottom of the left leg). A vertical line of light"
        " runs from a violet sphere above to an earthy sphere at the base (path 32 linking Yesod, "
        "Foundation, and Malkuth, the Kingdom). Palette: deep indigo #2A0A5E, near-black #1C1C1C, olive, "
        "citrine, russet and dark green (the four colours of earth), silver; soft cosmic light from the "
        "stars and ellipse. The whole image should feel like completion, wholeness and the dance of the "
        "manifested world."
    ),
}
